#+begin_html
<p align="center">
  <a href="https://github.com/d12frosted/elpa-mirror/actions/workflows/mirror.yaml"><img alt="mirror" src="https://github.com/d12frosted/elpa-mirror/actions/workflows/mirror.yaml/badge.svg"/></a>
  <a href="https://github.com/sponsors/d12frosted"><img alt="Sponsor" src="https://img.shields.io/badge/Sponsor-d12frosted-pink?logo=githubsponsors&logoColor=white"/></a>
</p>
#+end_html

* =elpa-mirror=

Mirrors for some Emacs package archives. These mirrors should be used only when
the official repository is temporarily down. Maintained using [[https://github.com/d12frosted/mirror-elpa][mirror-elpa]],
which refreshes the snapshot every few hours (the badge above shows whether the
latest run is healthy).

Available archives, each a top-level directory in this repository:

- =gnu= and =gnu-devel= ([[https://elpa.gnu.org/packages/][GNU ELPA]] and its development builds)
- =nongnu= and =nongnu-devel= ([[https://elpa.nongnu.org/nongnu/][NonGNU ELPA]] and its development builds)
- =melpa= and =stable-melpa= ([[https://melpa.org/][MELPA]] and [[https://stable.melpa.org/][MELPA Stable]])

These mirrors serve the standard =package.el= archive format, so they work with
any =package.el=-based setup (vanilla Emacs, Spacemacs). They do *not* work with
[[https://github.com/doomemacs/doomemacs][Doom Emacs]], which manages packages with [[https://github.com/radian-software/straight.el][straight.el]] and installs from
upstream Git rather than from ELPA archives.

** Usage - GitHub

Just setup =package-archives= in your =init.el= file (add or drop archives as
you need them):

#+BEGIN_SRC emacs-lisp
  (setq package-archives
        '(("gnu"    . "https://raw.githubusercontent.com/d12frosted/elpa-mirror/master/gnu/")
          ("nongnu" . "https://raw.githubusercontent.com/d12frosted/elpa-mirror/master/nongnu/")
          ("melpa"  . "https://raw.githubusercontent.com/d12frosted/elpa-mirror/master/melpa/")))
#+END_SRC

** Usage - Local

First, you need to clone this repository.

#+BEGIN_SRC bash
  $ git clone --depth 1 git@github.com:d12frosted/elpa-mirror.git ~/.elpa-mirror
#+END_SRC

And then setup =package-archives= in your =init.el= file.

#+BEGIN_SRC emacs-lisp
  (setq package-archives
        `(("gnu"    . ,(concat user-home-directory ".elpa-mirror/gnu/"))
          ("nongnu" . ,(concat user-home-directory ".elpa-mirror/nongnu/"))
          ("melpa"  . ,(concat user-home-directory ".elpa-mirror/melpa/"))))
#+END_SRC

** Usage with Spacemacs

To use =elpa-mirror= with Spacemacs, you need to modify
=configuration-layer-elpa-archives=. To do so, just add following code to the
=dotspacemacs/user-init= function.

#+BEGIN_SRC emacs-lisp
  ;; remote
  (setq configuration-layer-elpa-archives
        '(("gnu"    . "https://raw.githubusercontent.com/d12frosted/elpa-mirror/master/gnu/")
          ("nongnu" . "https://raw.githubusercontent.com/d12frosted/elpa-mirror/master/nongnu/")
          ("melpa"  . "https://raw.githubusercontent.com/d12frosted/elpa-mirror/master/melpa/")))

  ;; local
  (setq configuration-layer-elpa-archives
        `(("gnu"    . ,(concat user-home-directory ".elpa-mirror/gnu/"))
          ("nongnu" . ,(concat user-home-directory ".elpa-mirror/nongnu/"))
          ("melpa"  . ,(concat user-home-directory ".elpa-mirror/melpa/"))))
#+END_SRC

For more grained control over =package-archives= (e. g. if you wish to use the
mirror only when one of the official repositories is down) checkout how it's
implemented in Spacemacs.

* Support

If you enjoy this project, you can support its development via [[https://github.com/sponsors/d12frosted][GitHub Sponsors]] or [[https://www.patreon.com/d12frosted][Patreon]].
