(dockerfile-mode .
		 [(20220820 1433)
		  ((emacs
		    (24)))
		  "Major mode for editing Docker's Dockerfiles" single
		  ((:commit . "099bc8dcd744d3c416d52aeddab7b2499a12f2b9")
		   (:keywords "docker")
		   (:url . "https://github.com/spotify/dockerfile-mode"))])
