(dockerfile-mode .
		 [(20210828 1805)
		  ((emacs
		    (24)))
		  "Major mode for editing Docker's Dockerfiles" single
		  ((:commit . "628315e2e4ab2f269548126444234caa057b2c75")
		   (:keywords "docker")
		   (:url . "https://github.com/spotify/dockerfile-mode"))])
