(dockerfile-mode .
		 [(20220813 5)
		  ((emacs
		    (24)))
		  "Major mode for editing Docker's Dockerfiles" single
		  ((:commit . "73a8bcc25547b874e1983a75901f6c31708cd104")
		   (:keywords "docker")
		   (:url . "https://github.com/spotify/dockerfile-mode"))])
