(dockerfile-mode .
		 [(20201208 1348)
		  ((emacs
		    (24)))
		  "Major mode for editing Docker's Dockerfiles" single
		  ((:commit . "6a56c1cc1713b501040b08fdbf0c4159a4fe95f9")
		   (:url . "https://github.com/spotify/dockerfile-mode"))])
