(dockerfile-mode .
		 [(20210106 235)
		  ((emacs
		    (24)))
		  "Major mode for editing Docker's Dockerfiles" single
		  ((:commit . "58b7380189de21496235382900838aa0db2dcf92")
		   (:url . "https://github.com/spotify/dockerfile-mode"))])
