(dockerfile-mode .
		 [(20220806 1709)
		  ((emacs
		    (24)))
		  "Major mode for editing Docker's Dockerfiles" single
		  ((:commit . "c7e4e2541deb66d266f58c364e33a4a10cefbc2b")
		   (:keywords "docker")
		   (:url . "https://github.com/spotify/dockerfile-mode"))])
