(dockerfile-mode .
		 [(20210213 2118)
		  ((emacs
		    (24)))
		  "Major mode for editing Docker's Dockerfiles" single
		  ((:commit . "27a9f4d2f3cfcc4188955f27d1945850d850aed1")
		   (:url . "https://github.com/spotify/dockerfile-mode"))])
