(dockerfile-mode .
		 [(20211016 1545)
		  ((emacs
		    (24)))
		  "Major mode for editing Docker's Dockerfiles" single
		  ((:commit . "5db94549ce8b000ae35adf511c820ad228178052")
		   (:keywords "docker")
		   (:url . "https://github.com/spotify/dockerfile-mode"))])
