(dockerfile-mode .
		 [(20220822 2021)
		  ((emacs
		    (24)))
		  "Major mode for editing Docker's Dockerfiles" tar
		  ((:commit . "52c6c00da1d31c0b6c29c74335b3af63ed6bf06c")
		   (:keywords "docker" "languages" "processes" "tools")
		   (:url . "https://github.com/spotify/dockerfile-mode"))])
