(dockerfile-mode .
		 [(20210828 1805)
		  ((emacs
		    (24)))
		  "Major mode for editing Docker's Dockerfiles" single
		  ((:commit . "83bc055f5bcafabd3a10655a193fe8fe8b886867")
		   (:keywords "docker")
		   (:url . "https://github.com/spotify/dockerfile-mode"))])
