;;; tok-theme.el --- Comfy dark theme -*- lexical-binding: t; -*-

;; Author: Topi Kettunen <topi@topikettunen.com>
;; URL: https://github.com/topikettunen/tok-theme
;; Package-Version: 20220912.2053
;; Package-Commit: 20e6dacffae5d41f5c5071d880c3ea3f6b0e1a8e
;; Version: 0.1
;; Package-Requires: ((emacs "26.1"))

;; This is free and unencumbered software released into the public domain.
;; 
;; Anyone is free to copy, modify, publish, use, compile, sell, or
;; distribute this software, either in source code form or as a compiled
;; binary, for any purpose, commercial or non-commercial, and by any
;; means.
;; 
;; In jurisdictions that recognize copyright laws, the author or authors
;; of this software dedicate any and all copyright interest in the
;; software to the public domain. We make this dedication for the benefit
;; of the public at large and to the detriment of our heirs and
;; successors. We intend this dedication to be an overt act of
;; relinquishment in perpetuity of all present and future rights to this
;; software under copyright law.
;; 
;; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
;; EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
;; MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
;; IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
;; OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
;; ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
;; OTHER DEALINGS IN THE SOFTWARE.
;; 
;; For more information, please refer to <https://unlicense.org>

;; This file is not part of Emacs.

;;; Commentary:

;; Tok is a comfy dark coloured theme.

;;; Code:

(deftheme tok
  "Comfy dark theme")

(let ((class '((class color) (min-colors 89))))
  (custom-theme-set-faces
   'tok
   `(default ((,class (:foreground "white" :background "gray10"))))
   `(bold ((,class (:weight bold))))
   `(italic ((,class (:slant italic))))
   `(bold-italic ((,class (:weight bold :slant italic))))
   `(underline ((,class (:underline t))))
   `(shadow ((,class (:foreground "grey70"))))
   `(link ((,class (:underline t :foreground "cyan1"))))
   `(link-visited ((,class (:foreground "violet" :inherit link))))
   `(highlight ((,class (:background "darkolivegreen"))))
   `(region ((,class (,@(and (>= emacs-major-version 27) '(:extend t)) :background "blue3"))))
   `(secondary-selection ((,class (,@(and (>= emacs-major-version 27) '(:extend t)) :background "SkyBlue4"))))
   `(trailing-whitespace ((,class (:background "red1"))))
   `(line-number ((,class (:foreground "DarkGoldenrod1"))))
   `(line-number-current-line ((,class (:inherit line-number))))
   `(line-number-major-tick ((,class (:weight bold :background "grey75"))))
   `(line-number-minor-tick ((,class (:weight bold :background "grey55"))))
   `(fill-column-indicator ((,class (:weight normal :slant normal :inherit shadow))))
   `(escape-glyph ((,class (:foreground "cyan"))))
   `(homoglyph ((,class (:foreground "cyan"))))
   `(nobreak-space ((,class (:underline t :inherit escape-glyph))))
   `(nobreak-hyphen ((,class (:foreground "cyan"))))
   `(mode-line ((,class (:foreground "white" :background "grey10" :box (:line-width -1 :style released-button)))))
   (when (>= emacs-major-version 29)
     `(mode-line-active ((,class (:inherit mode-line)))))
   `(mode-line-inactive ((,class (:weight light :foreground "white" :background "grey20"))))
   `(mode-line-highlight ((t (nil))))
   `(mode-line-emphasis ((,class (:weight bold))))
   `(mode-line-buffer-id ((,class (:foreground "DarkGoldenrod1"))))
   `(header-line ((,class (:box nil :foreground "grey90" :background "grey20" :inherit mode-line))))
   `(header-line-highlight ((,class (:inherit mode-line-highlight))))
   `(vertical-border ((,class (:foreground "gray20"))))
   `(window-divider ((,class (:foreground "gray60"))))
   `(window-divider-first-pixel ((,class (:foreground "gray80"))))
   `(window-divider-last-pixel ((,class (:foreground "gray40"))))
   `(internal-border ((t (nil))))
   `(child-frame-border ((t (nil))))
   `(minibuffer-prompt ((,class (:foreground "cyan"))))
   `(fringe ((,class (:background "grey10"))))
   `(scroll-bar ((,class (:foreground "white"))))
   `(border ((t (nil))))
   `(cursor ((,class (:background "orange"))))
   `(mouse ((t (nil))))
   `(tool-bar ((,class (:foreground "black" :background "grey75"))))
   `(tab-bar ((,class (:foreground "black" :background "grey85" :inherit variable-pitch))))
   `(tab-line ((,class (:height 0.9 :foreground "black" :background "grey85" :inherit variable-pitch))))
   `(menu ((,class (:inverse-video t))))
   `(help-argument-name ((,class (:inherit italic))))
   `(help-key-binding ((,class (:foreground "LightBlue" :background "grey19"))))
   `(glyphless-char ((,class (:height 0.6))))
   `(error ((,class (:weight bold :foreground "Pink"))))
   `(warning ((,class (:weight bold :foreground "DarkOrange"))))
   `(success ((,class (:weight bold :foreground "Green1"))))
   `(read-multiple-choice-face ((,class (:weight bold :inherit underline))))
   `(tty-menu-enabled-face ((,class (:weight bold :foreground "yellow" :background "blue"))))
   `(tty-menu-disabled-face ((,class (:foreground "lightgray" :background "blue"))))
   `(tty-menu-selected-face ((,class (:background "red"))))
   `(show-paren-match ((,class (:background "steelblue3"))))
   `(show-paren-match-expression ((,class (:inherit show-paren-match))))
   `(show-paren-mismatch ((,class (:foreground "white" :background "purple"))))
   `(button ((,class (:inherit link))))
   `(next-error ((,class (:inherit region))))
   `(next-error-message ((,class (,@(and (>= emacs-major-version 27) '(:extend t)) :inherit highlight))))
   `(separator-line ((,class (:height 0.1 :background "#505050"))))
   `(help-for-help-header ((,class (:height 1.26))))
   `(completions-group-title ((,class (:slant italic :inherit shadow))))
   `(completions-group-separator ((,class (:strike-through t :inherit shadow))))
   `(completions-annotations ((t (nil))))
   `(completions-first-difference ((,class (:inherit bold))))
   `(completions-common-part ((,class (:foreground "lightblue"))))
   `(font-lock-comment-face ((,class (:foreground "chocolate1" :slant italic))))
   `(font-lock-comment-delimiter-face ((,class (:inherit font-lock-comment-face))))
   `(font-lock-string-face ((,class (:foreground "LightGoldenrod1"))))
   `(font-lock-doc-face ((,class (:inherit font-lock-string-face))))
   `(font-lock-doc-markup-face ((,class (:inherit font-lock-constant-face))))
   `(font-lock-keyword-face ((,class (:foreground "LightGoldenrod3"))))
   `(font-lock-builtin-face ((,class (:foreground "DarkGoldenrod3"))))
   `(font-lock-function-name-face ((t (nil))))
   `(font-lock-variable-name-face ((t (nil))))
   `(font-lock-type-face ((,class (:foreground "LightGoldenrod2"))))
   `(font-lock-constant-face ((t (nil))))
   `(font-lock-warning-face ((,class (:inherit error))))
   `(font-lock-negation-char-face ((t (nil))))
   `(font-lock-preprocessor-face ((,class (:inherit font-lock-builtin-face))))
   `(font-lock-regexp-grouping-backslash ((,class (:inherit bold))))
   `(font-lock-regexp-grouping-construct ((,class (:inherit bold))))
   `(mouse-drag-and-drop-region ((,class (:inherit region))))
   `(isearch ((,class (:foreground "brown4" :background "palevioletred2"))))
   `(isearch-fail ((,class (:background "red4"))))
   `(lazy-highlight ((,class (:background "paleturquoise4"))))
   `(isearch-group-1 ((,class (:foreground "brown4" :background "palevioletred1"))))
   `(isearch-group-2 ((,class (:foreground "brown4" :background "palevioletred3"))))
   `(file-name-shadow ((,class (:inherit shadow))))
   `(tab-bar-tab ((,class (:inherit tab-bar))))
   `(tab-bar-tab-inactive ((,class (:background "grey75" :inherit tab-bar-tab))))
   `(tab-bar-tab-group-current ((,class (:weight bold :box nil :inherit tab-bar-tab))))
   `(tab-bar-tab-group-inactive ((t (nil))))
   `(tab-bar-tab-ungrouped ((t (nil))))
   `(query-replace ((,class (:inherit isearch))))
   `(match ((,class (:background "RoyalBlue3"))))
   `(tabulated-list-fake-header ((,class (:weight bold :underline t :overline t))))
   `(buffer-menu-buffer ((,class (:weight bold))))
   `(ns-working-text-face ((,class (:underline t))))
   `(vc-state-base ((t (nil))))
   `(vc-up-to-date-state ((,class (:inherit vc-state-base))))
   `(vc-needs-update-state ((,class (:inherit vc-state-base))))
   `(vc-locked-state ((,class (:inherit vc-state-base))))
   `(vc-locally-added-state ((,class (:inherit vc-state-base))))
   `(vc-conflict-state ((,class (:inherit vc-state-base))))
   `(vc-removed-state ((,class (:inherit vc-state-base))))
   `(vc-missing-state ((,class (:inherit vc-state-base))))
   `(vc-edited-state ((,class (:inherit vc-state-base))))
   `(elisp-shorthand-font-lock-face ((,class (:foreground "cyan" :inherit font-lock-keyword-face))))
   `(eldoc-highlight-function-argument ((,class (:inherit bold))))
   `(tooltip ((,class (:foreground "black" :background "lightyellow" :inherit variable-pitch))))
   `(browse-url-button ((,class (:inherit link))))
   `(package-help-section-name ((t (nil))))
   `(package-name ((,class (:inherit link))))
   `(package-description ((,class (:inherit default))))
   `(package-status-built-in ((,class (:inherit font-lock-builtin-face))))
   `(package-status-external ((,class (:inherit package-status-built-in))))
   `(package-status-available ((,class (:inherit default))))
   `(package-status-new ((t (nil))))
   `(package-status-held ((,class (:inherit font-lock-constant-face))))
   `(package-status-disabled ((,class (:inherit font-lock-warning-face))))
   `(package-status-installed ((,class (:inherit font-lock-comment-face))))
   `(package-status-dependency ((,class (:inherit package-status-installed))))
   `(package-status-unsigned ((,class (:inherit font-lock-warning-face))))
   `(package-status-incompat ((,class (:inherit error))))
   `(package-status-avail-obso ((,class (:inherit package-status-incompat))))
   `(info-node ((,class (:weight bold :slant italic :foreground "white"))))
   `(info-title-1 ((,class (:height 1.2 :inherit info-title-2))))
   `(info-title-2 ((,class (:height 1.2 :inherit info-title-3))))
   `(info-title-3 ((,class (:height 1.2 :inherit info-title-4))))
   `(info-title-4 ((,class (:weight bold :inherit variable-pitch))))
   `(info-menu-header ((,class (:weight bold :inherit variable-pitch))))
   `(info-menu-star ((,class (:foreground "red1"))))
   `(info-xref ((,class (:inherit link))))
   `(info-xref-visited ((t (nil))))
   `(info-header-xref ((,class (:inherit info-xref))))
   `(info-header-node ((,class (:inherit info-node))))
   `(info-index-match ((,class (:inherit match))))
   `(Info-quoted ((,class (:inherit fixed-pitch-serif))))
   `(ido-first-match ((,class (:weight bold))))
   `(ido-only-match ((,class (:foreground "ForestGreen"))))
   `(ido-subdir ((,class (:foreground "red1"))))
   `(ido-virtual ((,class (:inherit font-lock-builtin-face))))
   `(ido-indicator ((,class (:width condensed :foreground "yellow1" :background "red1"))))
   `(ido-incomplete-regexp ((,class (:inherit font-lock-warning-face))))
   `(shortdoc-heading ((,class (:height 1.3 :weight bold :inherit variable-pitch))))
   `(shortdoc-section ((,class (:inherit variable-pitch))))
   `(corfu-default ((,class (:background "#191a1b"))))
   `(corfu-current ((,class (:foreground "white" :background "#00415e"))))
   `(corfu-bar ((,class (:background "#a8a8a8"))))
   `(corfu-border ((,class (:background "#323232"))))
   `(corfu-echo ((,class (:inherit completions-annotations))))
   `(corfu-annotations ((,class (:inherit completions-annotations))))
   `(corfu-deprecated ((,class (:strike-through t :inherit shadow))))
   `(ansi-color-bold ((t (nil))))
   `(ansi-color-faint ((,class (:weight light))))
   `(ansi-color-italic ((t (nil))))
   `(ansi-color-underline ((t (nil))))
   `(ansi-color-slow-blink ((t (nil))))
   `(ansi-color-fast-blink ((t (nil))))
   `(ansi-color-inverse ((,class (:inverse-video t))))
   `(ansi-color-black ((,class (:foreground "black" :background "black"))))
   `(ansi-color-red ((,class (:foreground "red3" :background "red3"))))
   `(ansi-color-green ((,class (:foreground "green3" :background "green3"))))
   `(ansi-color-yellow ((,class (:foreground "yellow3" :background "yellow3"))))
   `(ansi-color-blue ((,class (:foreground "blue2" :background "blue2"))))
   `(ansi-color-magenta ((,class (:foreground "magenta3" :background "magenta3"))))
   `(ansi-color-cyan ((,class (:foreground "cyan3" :background "cyan3"))))
   `(ansi-color-white ((,class (:foreground "grey90" :background "gray90"))))
   `(ansi-color-bright-black ((,class (:foreground "gray30" :background "gray30"))))
   `(ansi-color-bright-red ((,class (:foreground "red2" :background "red2"))))
   `(ansi-color-bright-green ((,class (:foreground "green2" :background "green2"))))
   `(ansi-color-bright-yellow ((,class (:foreground "yellow2" :background "yellow2"))))
   `(ansi-color-bright-blue ((,class (:foreground "blue1" :background "blue1"))))
   `(ansi-color-bright-magenta ((,class (:foreground "magenta2" :background "magenta2"))))
   `(ansi-color-bright-cyan ((,class (:foreground "cyan2" :background "cyan2"))))
   `(ansi-color-bright-white ((,class (:foreground "white" :background "white"))))
   `(comint-highlight-input ((,class (:weight bold))))
   `(comint-highlight-prompt ((,class (:inherit minibuffer-prompt))))
   `(term ((,class (:inherit default))))
   `(term-bold ((,class (:inherit ansi-color-bold))))
   `(term-underline ((,class (:inherit ansi-color-underline))))
   `(term-color-black ((,class (:inherit ansi-color-black))))
   `(term-color-red ((,class (:inherit ansi-color-red))))
   `(term-color-green ((,class (:inherit ansi-color-green))))
   `(term-color-yellow ((,class (:inherit ansi-color-yellow))))
   `(term-color-blue ((,class (:inherit ansi-color-blue))))
   `(term-color-magenta ((,class (:inherit ansi-color-magenta))))
   `(term-color-cyan ((,class (:inherit ansi-color-cyan))))
   `(term-color-white ((,class (:inherit ansi-color-white))))
   `(term-color-bright-black ((,class (:inherit ansi-color-bright-black))))
   `(term-color-bright-red ((,class (:inherit ansi-color-bright-red))))
   `(term-color-bright-green ((,class (:inherit ansi-color-bright-green))))
   `(term-color-bright-yellow ((,class (:inherit ansi-color-bright-yellow))))
   `(term-color-bright-blue ((,class (:inherit ansi-color-bright-blue))))
   `(term-color-bright-magenta ((,class (:inherit ansi-color-bright-magenta))))
   `(term-color-bright-cyan ((,class (:inherit ansi-color-bright-cyan))))
   `(term-color-bright-white ((,class (:inherit ansi-color-bright-white))))
   `(compilation-error ((,class (:inherit error))))
   `(compilation-warning ((,class (:inherit warning))))
   `(compilation-info ((,class (:inherit success))))
   `(compilation-mode-line-fail ((,class (:weight bold :foreground "Red1" :inherit compilation-error))))
   `(compilation-mode-line-run ((,class (:inherit compilation-warning))))
   `(compilation-mode-line-exit ((,class (:weight bold :foreground "ForestGreen" :inherit compilation-info))))
   `(compilation-line-number ((,class (:inherit font-lock-keyword-face))))
   `(compilation-column-number ((,class (:inherit font-lock-doc-face))))
   `(bookmark-menu-bookmark ((,class (:weight bold))))
   `(bookmark-menu-heading ((,class (:inherit font-lock-type-face))))
   `(bookmark-face ((,class (:foreground "DarkOrange1" :background "Black"))))
   `(vterm-color-black ((,class (:inherit term-color-black))))
   `(vterm-color-red ((,class (:inherit term-color-red))))
   `(vterm-color-green ((,class (:inherit term-color-green))))
   `(vterm-color-yellow ((,class (:inherit term-color-yellow))))
   `(vterm-color-blue ((,class (:inherit term-color-blue))))
   `(vterm-color-magenta ((,class (:inherit term-color-magenta))))
   `(vterm-color-cyan ((,class (:inherit term-color-cyan))))
   `(vterm-color-white ((,class (:inherit term-color-white))))
   `(vterm-color-underline ((,class (:inherit default))))
   `(vterm-color-inverse-video ((,class (:inherit default))))
   `(calendar-today ((,class (:underline t))))
   `(diary ((,class (:foreground "yellow1"))))
   `(holiday ((,class (:background "chocolate4"))))
   `(calendar-weekday-header ((,class (:inherit font-lock-constant-face))))
   `(calendar-weekend-header ((,class (:inherit font-lock-comment-face))))
   `(calendar-month-header ((,class (:inherit font-lock-function-name-face))))
   `(outline-1 ((t (nil))))
   `(outline-2 ((t (nil))))
   `(outline-3 ((t (nil))))
   `(outline-4 ((t (nil))))
   `(outline-5 ((t (nil))))
   `(outline-6 ((t (nil))))
   `(outline-7 ((t (nil))))
   `(outline-8 ((t (nil))))
   `(org-default ((,class (:inherit default))))
   `(org-hide ((,class (:foreground "black" :inherit fixed-pitch))))
   `(org-dispatcher-highlight ((,class (:weight bold :foreground "gold1" :background "gray20"))))
   `(org-level-1 ((,class (:extend nil :inherit outline-1))))
   `(org-level-2 ((,class (:extend nil :inherit outline-2))))
   `(org-level-3 ((,class (:extend nil :inherit outline-3))))
   `(org-level-4 ((,class (:extend nil :inherit outline-4))))
   `(org-level-5 ((,class (:extend nil :inherit outline-5))))
   `(org-level-6 ((,class (:extend nil :inherit outline-6))))
   `(org-level-7 ((,class (:extend nil :inherit outline-7))))
   `(org-level-8 ((,class (:extend nil :inherit outline-8))))
   `(org-special-keyword ((,class (:inherit font-lock-keyword-face))))
   `(org-drawer ((,class (:foreground "LightSkyBlue"))))
   `(org-property-value ((t (nil))))
   `(org-column ((,class (:weight normal :slant normal :underline nil :strike-through nil :background "grey30"))))
   `(org-column-title ((,class (:weight bold :underline t :background "grey30"))))
   `(org-agenda-column-dateline ((,class (:inherit org-column))))
   `(org-warning ((,class (:inherit font-lock-warning-face))))
   `(org-archived ((,class (:inherit shadow))))
   `(org-cite ((,class (:inherit link))))
   `(org-cite-key ((,class (:inherit link))))
   `(org-link ((,class (:inherit link))))
   `(org-footnote ((,class (:underline t :foreground "Cyan"))))
   `(org-ellipsis ((,class (:underline t :foreground "LightGoldenrod"))))
   `(org-target ((,class (:underline t))))
   `(org-date ((,class (:underline t :foreground "Cyan" :inherit fixed-pitch))))
   `(org-date-selected ((,class (:inverse-video t :foreground "Pink"))))
   `(org-sexp-date ((,class (:foreground "Cyan"))))
   `(org-tag ((,class (:weight bold))))
   `(org-list-dt ((,class (:weight bold))))
   `(org-todo ((,class (:weight bold :foreground "Pink"))))
   `(org-done ((,class (:weight bold :foreground "PaleGreen"))))
   `(org-agenda-done ((,class (:foreground "PaleGreen"))))
   `(org-headline-todo ((,class (:foreground "Pink2"))))
   `(org-headline-done ((,class (:foreground "LightSalmon"))))
   `(org-priority ((,class (:inherit font-lock-keyword-face))))
   `(org-checkbox ((,class (:inherit bold))))
   `(org-checkbox-statistics-todo ((,class (:inherit org-todo))))
   `(org-checkbox-statistics-done ((,class (:inherit org-done))))
   `(org-table ((,class (:foreground "LightSkyBlue" :inherit fixed-pitch))))
   `(org-table-header ((,class (:foreground "Black" :background "LightGray" :inherit org-table))))
   `(org-formula ((,class (:foreground "chocolate1" :inherit fixed-pitch))))
   `(org-code ((t (nil))))
   `(org-meta-line ((t (nil))))
   `(org-document-title ((,class (:weight bold :foreground "pale turquoise"))))
   `(org-document-info ((,class (:foreground "pale turquoise"))))
   `(org-document-info-keyword ((,class (:inherit shadow))))
   `(org-block ((,class (,@(and (>= emacs-major-version 27) '(:extend t))))))
   `(org-block-begin-line ((,class (,@(and (>= emacs-major-version 27) '(:extend t)) :inherit org-meta-line))))
   `(org-block-end-line ((,class (,@(and (>= emacs-major-version 27) '(:extend t)) :inherit org-block-begin-line))))
   `(org-verbatim ((t (nil))))
   `(org-quote ((,class (:inherit org-block))))
   `(org-verse ((,class (:inherit org-block))))
   `(org-clock-overlay ((,class (:foreground "white" :background "SkyBlue4"))))
   `(org-agenda-structure ((,class (:foreground "LightSkyBlue"))))
   `(org-agenda-structure-secondary ((,class (:inherit org-agenda-structure))))
   `(org-agenda-structure-filter ((t (nil))))
   `(org-agenda-date ((,class (:inherit org-agenda-structure))))
   `(org-agenda-date-today ((,class (:weight bold :slant italic :inherit org-agenda-date))))
   `(org-agenda-date-weekend-today ((,class (:inherit org-agenda-date-today))))
   `(org-agenda-clocking ((,class (:inherit secondary-selection))))
   `(org-agenda-date-weekend ((,class (:weight bold :inherit org-agenda-date))))
   `(org-scheduled ((,class (:foreground "PaleGreen"))))
   `(org-scheduled-today ((,class (:foreground "PaleGreen"))))
   `(org-agenda-dimmed-todo-face ((,class (:foreground "grey50"))))
   `(org-scheduled-previously ((,class (:foreground "chocolate1"))))
   `(org-imminent-deadline ((,class (:inherit org-warning))))
   `(org-upcoming-deadline ((,class (:foreground "chocolate1"))))
   `(org-upcoming-distant-deadline ((,class (:inherit org-default))))
   `(org-agenda-restriction-lock ((,class (:background "#1C1C1C"))))
   `(org-agenda-filter-tags ((,class (:inherit mode-line))))
   `(org-agenda-filter-category ((,class (:inherit mode-line))))
   `(org-agenda-filter-effort ((,class (:inherit mode-line))))
   `(org-agenda-filter-regexp ((,class (:inherit mode-line))))
   `(org-time-grid ((,class (:foreground "LightGoldenrod"))))
   `(org-agenda-current-time ((,class (:inherit org-time-grid))))
   `(org-agenda-diary ((,class (:inherit default))))
   `(org-agenda-calendar-event ((,class (:inherit default))))
   `(org-agenda-calendar-sexp ((,class (:inherit default))))
   `(org-latex-and-related ((,class (:foreground "burlywood"))))
   `(org-macro ((,class (:inherit org-latex-and-related))))
   `(org-tag-group ((,class (:inherit org-tag))))
   `(org-mode-line-clock ((,class (:inherit mode-line))))
   `(org-mode-line-clock-overrun ((,class (:background "red" :inherit mode-line))))
   `(dired-header ((,class (:inherit font-lock-type-face))))
   `(dired-mark ((,class (:inherit font-lock-constant-face))))
   `(dired-marked ((,class (:inherit warning))))
   `(dired-flagged ((,class (:inherit error))))
   `(dired-warning ((,class (:inherit font-lock-warning-face))))
   `(dired-perm-write ((,class (:inherit font-lock-comment-delimiter-face))))
   `(dired-set-id ((,class (:inherit font-lock-warning-face))))
   `(dired-directory ((,class (:inherit font-lock-function-name-face))))
   `(dired-symlink ((,class (:inherit font-lock-keyword-face))))
   `(dired-broken-symlink ((,class (:weight bold :foreground "yellow1" :background "red1"))))
   `(dired-special ((,class (:inherit font-lock-variable-name-face))))
   `(dired-ignored ((,class (:inherit shadow))))
   `(widget-documentation ((,class (:foreground "lime green"))))
   `(widget-button ((,class (:weight bold))))
   `(widget-field ((,class (,@(and (>= emacs-major-version 27) '(:extend t)) :background "dim gray"))))
   `(widget-single-line-field ((,class (:background "dim gray"))))
   `(widget-inactive ((,class (:inherit shadow))))
   `(widget-button-pressed ((,class (:foreground "red1"))))
   `(rmail-highlight ((,class (:inherit highlight))))
   `(rmail-header-name ((,class (:inherit font-lock-function-name-face))))
   `(gnus-group-news-1-empty ((,class (:foreground "PaleTurquoise"))))
   `(gnus-group-news-1 ((,class (:weight bold :inherit gnus-group-news-1-empty))))
   `(gnus-group-news-2-empty ((,class (:foreground "turquoise"))))
   `(gnus-group-news-2 ((,class (:weight bold :inherit gnus-group-news-2-empty))))
   `(gnus-group-news-3-empty ((t (nil))))
   `(gnus-group-news-3 ((,class (:weight bold :inherit gnus-group-news-3-empty))))
   `(gnus-group-news-4-empty ((t (nil))))
   `(gnus-group-news-4 ((,class (:weight bold :inherit gnus-group-news-4-empty))))
   `(gnus-group-news-5-empty ((t (nil))))
   `(gnus-group-news-5 ((,class (:weight bold :inherit gnus-group-news-5-empty))))
   `(gnus-group-news-6-empty ((t (nil))))
   `(gnus-group-news-6 ((,class (:weight bold :inherit gnus-group-news-6-empty))))
   `(gnus-group-news-low-empty ((,class (:foreground "DarkTurquoise"))))
   `(gnus-group-news-low ((,class (:weight bold :inherit gnus-group-news-low-empty))))
   `(gnus-group-mail-1-empty ((,class (:foreground "#e1ffe1"))))
   `(gnus-group-mail-1 ((,class (:weight bold :inherit gnus-group-mail-1-empty))))
   `(gnus-group-mail-2-empty ((,class (:foreground "DarkSeaGreen1"))))
   `(gnus-group-mail-2 ((,class (:weight bold :inherit gnus-group-mail-2-empty))))
   `(gnus-group-mail-3-empty ((,class (:foreground "aquamarine1"))))
   `(gnus-group-mail-3 ((,class (:weight bold :inherit gnus-group-mail-3-empty))))
   `(gnus-group-mail-low-empty ((,class (:foreground "aquamarine2"))))
   `(gnus-group-mail-low ((,class (:weight bold :inherit gnus-group-mail-low-empty))))
   `(gnus-summary-selected ((,class (:underline t ,@(and (>= emacs-major-version 27) '(:extend t))))))
   `(gnus-summary-cancelled ((,class (,@(and (>= emacs-major-version 27) '(:extend t)) :foreground "yellow" :background "black"))))
   `(gnus-summary-normal-ticked ((,class (,@(and (>= emacs-major-version 27) '(:extend t)) :foreground "pink"))))
   `(gnus-summary-high-ticked ((,class (:weight bold :inherit gnus-summary-normal-ticked))))
   `(gnus-summary-low-ticked ((,class (:slant italic :inherit gnus-summary-normal-ticked))))
   `(gnus-summary-normal-ancient ((,class (,@(and (>= emacs-major-version 27) '(:extend t)) :foreground "SkyBlue"))))
   `(gnus-summary-high-ancient ((,class (:weight bold :inherit gnus-summary-normal-ancient))))
   `(gnus-summary-low-ancient ((,class (:slant italic :inherit gnus-summary-normal-ancient))))
   `(gnus-summary-normal-undownloaded ((,class (:weight normal ,@(and (>= emacs-major-version 27) '(:extend t)) :foreground "cyan4"))))
   `(gnus-summary-high-undownloaded ((,class (:weight bold :inherit gnus-summary-normal-undownloaded))))
   `(gnus-summary-low-undownloaded ((,class (:slant italic :inherit gnus-summary-normal-undownloaded))))
   `(gnus-summary-normal-unread ((,class (,@(and (>= emacs-major-version 27) '(:extend t))))))
   `(gnus-summary-high-unread ((,class (:weight bold :inherit gnus-summary-normal-unread))))
   `(gnus-summary-low-unread ((,class (:slant italic :inherit gnus-summary-normal-unread))))
   `(gnus-summary-normal-read ((,class (,@(and (>= emacs-major-version 27) '(:extend t)) :foreground "PaleGreen"))))
   `(gnus-summary-high-read ((,class (:weight bold :inherit gnus-summary-normal-read))))
   `(gnus-summary-low-read ((,class (:slant italic :inherit gnus-summary-normal-read))))
   `(gnus-splash ((,class (:foreground "#cccccc"))))
   `(mm-command-output ((,class (:foreground "ForestGreen"))))
   `(epa-validity-high ((,class (:weight bold :foreground "PaleTurquoise"))))
   `(epa-validity-medium ((,class (:slant italic :foreground "PaleTurquoise"))))
   `(epa-validity-low ((,class (:slant italic))))
   `(epa-validity-disabled ((,class (:slant italic :inverse-video t))))
   `(epa-string ((,class (:foreground "lightyellow"))))
   `(epa-mark ((,class (:weight bold :foreground "orange"))))
   `(epa-field-name ((,class (:weight bold :foreground "PaleTurquoise"))))
   `(epa-field-body ((,class (:slant italic :foreground "turquoise"))))
   `(message-header-to ((,class (:weight bold :foreground "DarkOliveGreen1"))))
   `(message-header-cc ((,class (:weight bold :foreground "chartreuse1"))))
   `(message-header-subject ((,class (:foreground "OliveDrab1"))))
   `(message-header-newsgroups ((,class (:weight bold :slant italic :foreground "yellow"))))
   `(message-header-other ((,class (:foreground "VioletRed1"))))
   `(message-header-name ((,class (:foreground "green"))))
   `(message-header-xheader ((,class (:foreground "DeepSkyBlue1"))))
   `(message-separator ((,class (:foreground "LightSkyBlue1"))))
   `(message-cited-text-1 ((,class (:foreground "LightPink1"))))
   `(message-cited-text-2 ((,class (:foreground "forest green"))))
   `(message-cited-text-3 ((,class (:foreground "goldenrod3"))))
   `(message-cited-text-4 ((,class (:foreground "chocolate3"))))
   `(message-mml ((,class (:foreground "MediumSpringGreen"))))
   `(message-signature-separator ((,class (:weight bold))))
   `(shr-strike-through ((,class (:strike-through t))))
   `(shr-link ((,class (:inherit link))))
   `(shr-selected-link ((,class (:background "red" :inherit shr-link))))
   `(shr-abbreviation ((,class (:inherit underline))))
   `(shr-h1 ((,class (:height 1.3 :weight bold))))
   `(shr-h2 ((,class (:weight bold))))
   `(shr-h3 ((,class (:slant italic))))
   `(shr-h4 ((t (nil))))
   `(shr-h5 ((t (nil))))
   `(shr-h6 ((t (nil))))
   `(mm-uu-extract ((,class (,@(and (>= emacs-major-version 27) '(:extend t)) :foreground "light yellow" :background "dark green"))))
   `(gnus-emphasis-bold ((,class (:weight bold))))
   `(gnus-emphasis-italic ((,class (:slant italic))))
   `(gnus-emphasis-underline ((,class (:underline t))))
   `(gnus-emphasis-underline-bold ((,class (:weight bold :underline t))))
   `(gnus-emphasis-underline-italic ((,class (:slant italic :underline t))))
   `(gnus-emphasis-bold-italic ((,class (:weight bold :slant italic))))
   `(gnus-emphasis-underline-bold-italic ((,class (:weight bold :slant italic :underline t))))
   `(gnus-emphasis-strikethru ((,class (:strike-through t))))
   `(gnus-emphasis-highlight-words ((,class (:foreground "yellow" :background "black"))))
   `(gnus-button ((,class (:weight bold))))
   `(gnus-signature ((,class (:slant italic))))
   `(gnus-header-from ((,class (:foreground "PaleGreen1"))))
   `(gnus-header-subject ((,class (:foreground "SeaGreen1"))))
   `(gnus-header-newsgroups ((,class (:slant italic :foreground "yellow"))))
   `(gnus-header-name ((,class (:foreground "SpringGreen2"))))
   `(gnus-header-content ((,class (:slant italic :foreground "SpringGreen1"))))
   `(speedbar-button-face ((,class (:foreground "green3"))))
   `(speedbar-file-face ((,class (:foreground "cyan"))))
   `(speedbar-directory-face ((,class (:foreground "light blue"))))
   `(speedbar-tag-face ((,class (:foreground "yellow"))))
   `(speedbar-selected-face ((,class (:underline t :foreground "red"))))
   `(speedbar-highlight-face ((,class (:background "sea green"))))
   `(speedbar-separator-face ((,class (:overline "gray" :foreground "white" :background "blue"))))
   `(eww-form-submit ((,class (:foreground "black" :background "#808080"))))
   `(eww-form-file ((,class (:foreground "black" :background "#808080"))))
   `(eww-form-checkbox ((,class (:foreground "black" :background "lightgrey"))))
   `(eww-form-select ((,class (:foreground "black" :background "lightgrey"))))
   `(eww-form-text ((,class (:foreground "white" :background "#505050"))))
   `(eww-form-textarea ((,class (:foreground "black" :background "#C0C0C0"))))
   `(eww-invalid-certificate ((,class (:weight bold :foreground "red"))))
   `(eww-valid-certificate ((,class (:weight bold :foreground "ForestGreen"))))
   `(diary-anniversary ((,class (:inherit font-lock-keyword-face))))
   `(diary-time ((,class (:inherit font-lock-variable-name-face))))
   `(diary-button ((t (nil))))
   `(yas-field-highlight-face ((,class (:inherit region))))
   `(yas--field-debug-face ((t (nil))))
   `(diff-header ((,class (,@(and (>= emacs-major-version 27) '(:extend t)) :background "grey45"))))
   `(diff-file-header ((,class (:weight bold ,@(and (>= emacs-major-version 27) '(:extend t)) :background "grey60"))))
   `(diff-index ((,class (:inherit diff-file-header))))
   `(diff-hunk-header ((,class (:inherit diff-header))))
   `(diff-removed ((,class (,@(and (>= emacs-major-version 27) '(:extend t)) :background "#553333" :inherit diff-changed))))
   `(diff-added ((,class (,@(and (>= emacs-major-version 27) '(:extend t)) :background "#335533" :inherit diff-changed))))
   `(diff-changed-unspecified ((,class (,@(and (>= emacs-major-version 27) '(:extend t)) :background "grey20" :inherit diff-changed))))
   `(diff-changed ((t (nil))))
   `(diff-indicator-removed ((,class (:foreground "#aa2222" :inherit diff-removed))))
   `(diff-indicator-added ((,class (:foreground "#22aa22" :inherit diff-added))))
   `(diff-indicator-changed ((,class (:foreground "#aaaa22" :inherit diff-changed))))
   `(diff-function ((,class (:inherit diff-header))))
   `(diff-context ((,class (,@(and (>= emacs-major-version 27) '(:extend t))))))
   `(diff-nonexistent ((,class (:inherit diff-file-header))))
   `(diff-error ((,class (:weight bold :foreground "red" :background "black"))))
   `(diff-refine-changed ((,class (:background "#aaaa22"))))
   `(diff-refine-removed ((,class (:background "#aa2222" :inherit diff-refine-changed))))
   `(diff-refine-added ((,class (:background "#22aa22" :inherit diff-refine-changed))))
   `(hl-line ((,class (,@(and (>= emacs-major-version 27) '(:extend t)) :inherit highlight))))
   `(erc-default-face ((t (nil))))
   `(erc-nick-prefix-face ((,class (:weight bold :inherit erc-nick-default-face))))
   `(erc-my-nick-prefix-face ((,class (:weight bold :inherit erc-nick-default-face))))
   `(erc-direct-msg-face ((,class (:foreground "IndianRed"))))
   `(erc-header-line ((,class (:inherit header-line))))
   `(erc-input-face ((,class (:foreground "brown"))))
   `(erc-prompt-face ((,class (:weight bold :foreground "Black" :background "lightBlue2"))))
   `(erc-command-indicator-face ((,class (:weight bold))))
   `(erc-notice-face ((,class (:weight bold :foreground "SlateBlue"))))
   `(erc-action-face ((,class (:weight bold))))
   `(erc-error-face ((,class (:foreground "red"))))
   `(erc-my-nick-face ((,class (:weight bold :foreground "brown"))))
   `(erc-nick-default-face ((,class (:weight bold))))
   `(erc-nick-msg-face ((,class (:weight bold :foreground "IndianRed"))))
   `(erc-bold-face ((,class (:weight bold))))
   `(erc-italic-face ((,class (:slant italic))))
   `(erc-inverse-face ((,class (:foreground "White" :background "Black"))))
   `(erc-underline-face ((,class (:underline t))))
   `(fg:erc-color-face0 ((,class (:foreground "White"))))
   `(fg:erc-color-face1 ((,class (:foreground "black"))))
   `(fg:erc-color-face2 ((,class (:foreground "blue4"))))
   `(fg:erc-color-face3 ((,class (:foreground "green4"))))
   `(fg:erc-color-face4 ((,class (:foreground "red"))))
   `(fg:erc-color-face5 ((,class (:foreground "brown"))))
   `(fg:erc-color-face6 ((,class (:foreground "purple"))))
   `(fg:erc-color-face7 ((,class (:foreground "orange"))))
   `(fg:erc-color-face8 ((,class (:foreground "yellow"))))
   `(fg:erc-color-face9 ((,class (:foreground "green"))))
   `(fg:erc-color-face10 ((,class (:foreground "lightblue1"))))
   `(fg:erc-color-face11 ((,class (:foreground "cyan"))))
   `(fg:erc-color-face12 ((,class (:foreground "blue"))))
   `(fg:erc-color-face13 ((,class (:foreground "deeppink"))))
   `(fg:erc-color-face14 ((,class (:foreground "gray50"))))
   `(fg:erc-color-face15 ((,class (:foreground "gray90"))))
   `(bg:erc-color-face0 ((,class (:background "White"))))
   `(bg:erc-color-face1 ((,class (:background "black"))))
   `(bg:erc-color-face2 ((,class (:background "blue4"))))
   `(bg:erc-color-face3 ((,class (:background "green4"))))
   `(bg:erc-color-face4 ((,class (:background "red"))))
   `(bg:erc-color-face5 ((,class (:background "brown"))))
   `(bg:erc-color-face6 ((,class (:background "purple"))))
   `(bg:erc-color-face7 ((,class (:background "orange"))))
   `(bg:erc-color-face8 ((,class (:background "yellow"))))
   `(bg:erc-color-face9 ((,class (:background "green"))))
   `(bg:erc-color-face10 ((,class (:background "lightblue1"))))
   `(bg:erc-color-face11 ((,class (:background "cyan"))))
   `(bg:erc-color-face12 ((,class (:background "blue"))))
   `(bg:erc-color-face13 ((,class (:background "deeppink"))))
   `(bg:erc-color-face14 ((,class (:background "gray50"))))
   `(bg:erc-color-face15 ((,class (:background "gray90"))))
   `(erc-timestamp-face ((,class (:weight bold :foreground "green"))))
   `(erc-button ((,class (:weight bold))))
   `(erc-current-nick-face ((,class (:weight bold :foreground "DarkTurquoise"))))
   `(erc-dangerous-host-face ((,class (:foreground "red"))))
   `(erc-pal-face ((,class (:weight bold :foreground "Magenta"))))
   `(erc-fool-face ((,class (:foreground "dim gray"))))
   `(erc-keyword-face ((,class (:weight bold :foreground "pale green"))))
   `(magit-section-highlight ((,class (:extend t :background "grey20"))))
   `(magit-section-heading ((,class (:weight bold :extend t :foreground "LightGoldenrod2"))))
   `(magit-section-secondary-heading ((,class (:weight bold :extend t))))
   `(magit-section-heading-selection ((,class (:extend t :foreground "LightSalmon3"))))
   `(magit-section-child-count ((t (nil))))
   `(transient-heading ((,class (:inherit font-lock-keyword-face))))
   `(transient-key ((,class (:inherit font-lock-builtin-face))))
   `(transient-argument ((,class (:inherit font-lock-warning-face))))
   `(transient-value ((,class (:inherit font-lock-string-face))))
   `(transient-inactive-argument ((,class (:inherit shadow))))
   `(transient-inactive-value ((,class (:inherit shadow))))
   `(transient-unreachable ((,class (:inherit shadow))))
   `(transient-active-infix ((,class (:inherit secondary-selection))))
   `(transient-unreachable-key ((t (nil))))
   `(transient-nonstandard-key ((,class (:underline t))))
   `(transient-mismatched-key ((,class (:underline t))))
   `(transient-inapt-suffix ((,class (:slant italic :inherit shadow))))
   `(transient-enabled-suffix ((,class (:weight bold :foreground "black" :background "green"))))
   `(transient-disabled-suffix ((,class (:weight bold :foreground "black" :background "red"))))
   `(transient-higher-level ((,class (:underline t))))
   `(transient-separator ((,class (:extend t :background "grey30"))))
   `(transient-red ((,class (:foreground "red" :inherit transient-key))))
   `(transient-blue ((,class (:foreground "blue" :inherit transient-key))))
   `(transient-amaranth ((,class (:foreground "#E52B50" :inherit transient-key))))
   `(transient-pink ((,class (:foreground "#FF6EB4" :inherit transient-key))))
   `(transient-teal ((,class (:foreground "#367588" :inherit transient-key))))
   `(transient-purple ((,class (:foreground "#a020f0" :inherit transient-key))))
   `(magit-process-ok ((,class (:foreground "green" :inherit magit-section-heading))))
   `(magit-process-ng ((,class (:foreground "red" :inherit magit-section-heading))))
   `(magit-mode-line-process ((,class (:inherit mode-line-emphasis))))
   `(magit-mode-line-process-error ((,class (:inherit error))))
   `(change-log-date ((,class (:inherit font-lock-string-face))))
   `(change-log-name ((,class (:inherit font-lock-constant-face))))
   `(change-log-email ((,class (:inherit font-lock-variable-name-face))))
   `(change-log-file ((,class (:inherit font-lock-function-name-face))))
   `(change-log-list ((,class (:inherit font-lock-keyword-face))))
   `(change-log-conditionals ((,class (:inherit font-lock-variable-name-face))))
   `(change-log-function ((,class (:inherit font-lock-variable-name-face))))
   `(change-log-acknowledgment ((,class (:inherit font-lock-comment-face))))
   `(log-edit-summary ((,class (:inherit font-lock-function-name-face))))
   `(log-edit-header ((,class (:inherit font-lock-keyword-face))))
   `(log-edit-unknown-header ((,class (:inherit font-lock-comment-face))))
   `(git-commit-summary ((,class (:inherit font-lock-type-face))))
   `(git-commit-overlong-summary ((,class (:inherit font-lock-warning-face))))
   `(git-commit-nonempty-second-line ((,class (:inherit font-lock-warning-face))))
   `(git-commit-keyword ((,class (:inherit font-lock-string-face))))
   `(git-commit-pseudo-header ((,class (:inherit font-lock-string-face))))
   `(git-commit-known-pseudo-header ((,class (:inherit font-lock-keyword-face))))
   `(git-commit-comment-branch-local ((,class (:inherit font-lock-variable-name-face))))
   `(git-commit-comment-branch-remote ((,class (:inherit font-lock-variable-name-face))))
   `(git-commit-comment-detached ((,class (:inherit git-commit-comment-branch-local))))
   `(git-commit-comment-heading ((,class (:inherit git-commit-known-pseudo-header))))
   `(git-commit-comment-file ((,class (:inherit git-commit-pseudo-header))))
   `(git-commit-comment-action ((,class (:inherit bold))))
   `(smerge-upper ((,class (:extend t :background "#553333"))))
   `(smerge-lower ((,class (:extend t :background "#335533"))))
   `(smerge-base ((,class (:extend t :background "#888833"))))
   `(smerge-markers ((,class (:extend t :background "grey30"))))
   `(smerge-refined-changed ((t (nil))))
   `(smerge-refined-removed ((,class (:background "#aa2222" :inherit smerge-refined-change))))
   `(smerge-refined-added ((,class (:background "#22aa22" :inherit smerge-refined-change))))
   `(magit-diff-file-heading ((,class (:weight bold :extend t))))
   `(magit-diff-file-heading-highlight ((,class (:extend t :inherit magit-section-highlight))))
   `(magit-diff-file-heading-selection ((,class (:extend t :foreground "LightSalmon3" :inherit magit-diff-file-heading-highlight))))
   `(magit-diff-hunk-heading ((,class (:extend t :foreground "grey95" :background "grey25"))))
   `(magit-diff-hunk-heading-highlight ((,class (:extend t :foreground "grey95" :background "grey35"))))
   `(magit-diff-hunk-heading-selection ((,class (:extend t :foreground "LightSalmon3" :inherit magit-diff-hunk-heading-highlight))))
   `(magit-diff-hunk-region ((,class (:extend t :inherit bold))))
   `(magit-diff-revision-summary ((,class (:inherit magit-diff-hunk-heading))))
   `(magit-diff-revision-summary-highlight ((,class (:inherit magit-diff-hunk-heading-highlight))))
   `(magit-diff-lines-heading ((,class (:extend t :foreground "grey80" :background "salmon4" :inherit magit-diff-hunk-heading-highlight))))
   `(magit-diff-lines-boundary ((,class (:extend t :inherit magit-diff-lines-heading))))
   `(magit-diff-conflict-heading ((,class (:inherit magit-diff-hunk-heading))))
   `(magit-diff-added ((,class (:extend t :foreground "#ddffdd" :background "#335533"))))
   `(magit-diff-removed ((,class (:extend t :foreground "#ffdddd" :background "#553333"))))
   `(magit-diff-our ((,class (:inherit magit-diff-removed))))
   `(magit-diff-base ((,class (:extend t :foreground "#ffffcc" :background "#555522"))))
   `(magit-diff-their ((,class (:inherit magit-diff-added))))
   `(magit-diff-context ((,class (:extend t :foreground "grey70"))))
   `(magit-diff-added-highlight ((,class (:extend t :foreground "#cceecc" :background "#336633"))))
   `(magit-diff-removed-highlight ((,class (:extend t :foreground "#eecccc" :background "#663333"))))
   `(magit-diff-our-highlight ((,class (:inherit magit-diff-removed-highlight))))
   `(magit-diff-base-highlight ((,class (:extend t :foreground "#eeeebb" :background "#666622"))))
   `(magit-diff-their-highlight ((,class (:inherit magit-diff-added-highlight))))
   `(magit-diff-context-highlight ((,class (:extend t :foreground "grey70" :background "grey20"))))
   `(magit-diff-whitespace-warning ((,class (:inherit trailing-whitespace))))
   `(magit-diffstat-added ((,class (:foreground "#448844"))))
   `(magit-diffstat-removed ((,class (:foreground "#aa4444"))))
   `(which-func ((,class (:foreground "Blue1"))))
   `(magit-log-graph ((,class (:foreground "grey80"))))
   `(magit-log-author ((,class (:weight normal :slant normal :foreground "tomato"))))
   `(magit-log-date ((,class (:weight normal :slant normal :foreground "grey80"))))
   `(magit-header-line-log-select ((,class (:inherit bold))))
   `(magit-header-line ((,class (:inherit magit-section-heading))))
   `(magit-header-line-key ((,class (:inherit font-lock-builtin-face))))
   `(magit-dimmed ((,class (:foreground "grey50"))))
   `(magit-hash ((,class (:foreground "grey40"))))
   `(magit-tag ((,class (:foreground "LightGoldenrod2"))))
   `(magit-branch-remote ((,class (:foreground "DarkSeaGreen2"))))
   `(magit-branch-remote-head ((,class (:box 1 :inherit magit-branch-remote))))
   `(magit-branch-local ((,class (:foreground "LightSkyBlue1"))))
   `(magit-branch-current ((,class (:box 1 :inherit magit-branch-local))))
   `(magit-branch-upstream ((,class (:slant italic))))
   `(magit-branch-warning ((,class (:inherit warning))))
   `(magit-head ((,class (:inherit magit-branch-local))))
   `(magit-refname ((,class (:foreground "grey80"))))
   `(magit-refname-stash ((,class (:inherit magit-refname))))
   `(magit-refname-wip ((,class (:inherit magit-refname))))
   `(magit-refname-pullreq ((,class (:inherit magit-refname))))
   `(magit-keyword ((,class (:inherit font-lock-string-face))))
   `(magit-keyword-squash ((,class (:inherit font-lock-warning-face))))
   `(magit-signature-good ((,class (:foreground "green"))))
   `(magit-signature-bad ((,class (:weight bold :foreground "red"))))
   `(magit-signature-untrusted ((,class (:foreground "medium aquamarine"))))
   `(magit-signature-expired ((,class (:foreground "orange"))))
   `(magit-signature-expired-key ((,class (:inherit magit-signature-expired))))
   `(magit-signature-revoked ((,class (:foreground "violet red"))))
   `(magit-signature-error ((,class (:foreground "light blue"))))
   `(magit-cherry-unmatched ((,class (:foreground "cyan"))))
   `(magit-cherry-equivalent ((,class (:foreground "magenta"))))
   `(magit-filename ((,class (:weight normal))))
   `(magit-sequence-pick ((,class (:inherit default))))
   `(magit-sequence-stop ((,class (:foreground "DarkSeaGreen2"))))
   `(magit-sequence-part ((,class (:foreground "LightGoldenrod2"))))
   `(magit-sequence-head ((,class (:foreground "LightSkyBlue1"))))
   `(magit-sequence-drop ((,class (:foreground "IndianRed"))))
   `(magit-sequence-done ((,class (:inherit magit-hash))))
   `(magit-sequence-onto ((,class (:inherit magit-sequence-done))))
   `(magit-sequence-exec ((,class (:inherit magit-hash))))
   `(magit-bisect-good ((,class (:foreground "DarkOliveGreen"))))
   `(magit-bisect-skip ((,class (:foreground "DarkGoldenrod"))))
   `(magit-bisect-bad ((,class (:foreground "IndianRed4"))))
   `(magit-reflog-commit ((,class (:foreground "green"))))
   `(magit-reflog-amend ((,class (:foreground "magenta"))))
   `(magit-reflog-merge ((,class (:foreground "green"))))
   `(magit-reflog-checkout ((,class (:foreground "blue"))))
   `(magit-reflog-reset ((,class (:foreground "red"))))
   `(magit-reflog-rebase ((,class (:foreground "magenta"))))
   `(magit-reflog-cherry-pick ((,class (:foreground "green"))))
   `(magit-reflog-remote ((,class (:foreground "cyan"))))
   `(magit-reflog-other ((,class (:foreground "cyan"))))
   `(magit-blame-highlight ((,class (:extend t :foreground "white" :background "grey25"))))
   `(magit-blame-margin ((,class (:weight normal :slant normal :inherit magit-blame-highlight))))
   `(magit-blame-dimmed ((,class (:weight normal :slant normal :inherit magit-dimmed))))
   `(magit-blame-heading ((,class (:weight normal :slant normal :extend t :inherit magit-blame-highlight))))
   `(magit-blame-summary ((t (nil))))
   `(magit-blame-hash ((t (nil))))
   `(magit-blame-name ((t (nil))))
   `(magit-blame-date ((t (nil))))
   `(sh-heredoc ((t nil)))
   `(sh-quoted-exec ((t nil)))
   `(terraform--resource-name-face ((t nil)))
   `(terraform--resource-type-face ((t nil)))
   `(markdown-italic-face ((,class (:inherit italic))))
   `(markdown-bold-face ((,class (:inherit bold))))
   `(markdown-strike-through-face ((,class (:strike-through t))))
   `(markdown-markup-face ((,class (:weight normal :slant normal :inherit shadow))))
   `(markdown-header-rule-face ((,class (:inherit markdown-markup-face))))
   `(markdown-header-delimiter-face ((,class (:inherit markdown-markup-face))))
   `(markdown-list-face ((,class (:inherit markdown-markup-face))))
   `(markdown-blockquote-face ((,class (:inherit font-lock-doc-face))))
   `(markdown-code-face ((,class (:inherit fixed-pitch))))
   `(markdown-inline-code-face ((t (nil))))
   `(markdown-pre-face ((t (nil))))
   `(markdown-table-face ((t (nil))))
   `(markdown-language-keyword-face ((,class (:inherit font-lock-type-face))))
   `(markdown-language-info-face ((,class (:inherit font-lock-string-face))))
   `(markdown-link-face ((,class (:inherit link))))
   `(markdown-missing-link-face ((,class (:inherit font-lock-warning-face))))
   `(markdown-reference-face ((,class (:inherit markdown-markup-face))))
   `(markdown-footnote-marker-face ((,class (:inherit markdown-markup-face))))
   `(markdown-footnote-text-face ((,class (:inherit font-lock-comment-face))))
   `(markdown-url-face ((,class (:inherit font-lock-string-face))))
   `(markdown-plain-url-face ((,class (:inherit markdown-link-face))))
   `(markdown-link-title-face ((,class (:inherit font-lock-comment-face))))
   `(markdown-line-break-face ((,class (:underline t :inherit font-lock-constant-face))))
   `(markdown-comment-face ((,class (:inherit font-lock-comment-face))))
   `(markdown-math-face ((,class (:inherit font-lock-string-face))))
   `(markdown-metadata-key-face ((,class (:inherit font-lock-variable-name-face))))
   `(markdown-metadata-value-face ((,class (:inherit font-lock-string-face))))
   `(markdown-gfm-checkbox-face ((,class (:inherit font-lock-builtin-face))))
   `(markdown-highlight-face ((,class (:inherit highlight))))
   `(markdown-hr-face ((,class (:inherit markdown-markup-face))))
   `(markdown-html-tag-name-face ((,class (:inherit font-lock-type-face))))
   `(markdown-html-tag-delimiter-face ((,class (:inherit markdown-markup-face))))
   `(markdown-html-attr-name-face ((,class (:inherit font-lock-variable-name-face))))
   `(markdown-html-attr-value-face ((,class (:inherit font-lock-string-face))))
   `(markdown-html-entity-face ((,class (:inherit font-lock-variable-name-face))))
   `(markdown-highlighting-face ((,class (:foreground "black" :background "yellow"))))
   `(markdown-header-face ((,class (:weight bold))))
   `(markdown-header-face-1 ((,class (:height 1.0 :inherit markdown-header-face))))
   `(markdown-header-face-2 ((,class (:height 1.0 :inherit markdown-header-face))))
   `(markdown-header-face-3 ((,class (:height 1.0 :inherit markdown-header-face))))
   `(markdown-header-face-4 ((,class (:height 1.0 :inherit markdown-header-face))))
   `(markdown-header-face-5 ((,class (:height 1.0 :inherit markdown-header-face))))
   `(markdown-header-face-6 ((,class (:height 1.0 :inherit markdown-header-face))))
   `(xref-file-header ((,class (:inherit compilation-info))))
   `(xref-line-number ((,class (:inherit compilation-line-number))))
   `(xref-match ((,class (:inherit match))))
   `(ffap ((,class (:inherit highlight))))
   `(go-coverage-untracked ((,class (:foreground "#505050"))))
   `(go-coverage-0 ((,class (:foreground "#c00000"))))
   `(go-coverage-1 ((,class (:foreground "#808080"))))
   `(go-coverage-2 ((,class (:foreground "#748c83"))))
   `(go-coverage-3 ((,class (:foreground "#689886"))))
   `(go-coverage-4 ((,class (:foreground "#5ca489"))))
   `(go-coverage-5 ((,class (:foreground "#50b08c"))))
   `(go-coverage-6 ((,class (:foreground "#44bc8f"))))
   `(go-coverage-7 ((,class (:foreground "#38c892"))))
   `(go-coverage-8 ((,class (:foreground "#2cd495"))))
   `(go-coverage-9 ((,class (:foreground "#20e098"))))
   `(go-coverage-10 ((,class (:foreground "#14ec9b"))))
   `(go-coverage-covered ((,class (:foreground "#2cd495"))))
   `(go-dot-mod-module-name ((,class (:inherit default))))
   `(go-dot-mod-module-version ((,class (:inherit default))))
   `(go-dot-mod-module-semver ((,class (:inherit go-dot-mod-module-version))))
   `(flymake-error ((t (nil))))
   `(flymake-warning ((t (nil))))
   `(flymake-note ((t (nil))))
   `(ert-test-result-expected ((,class (:background "green3"))))
   `(ert-test-result-unexpected ((,class (:background "red3"))))
   `(eglot-highlight-symbol-face ((,class (:inherit bold))))
   `(eglot-mode-line ((,class (:weight bold :inherit font-lock-constant-face))))
   `(eglot-diagnostic-tag-unnecessary-face ((,class (:inherit shadow))))
   `(eglot-diagnostic-tag-deprecated-face ((,class (:strike-through t :inherit shadow))))
   `(ibuffer-locked-buffer ((,class (:foreground "RosyBrown"))))
   `(c-annotation-face ((,class (:inherit font-lock-constant-face))))
   `(c-nonbreakable-space-face ((,class (:foreground "gray10" :background "white"))))
   `(rectangle-preview ((,class (:inherit region))))
   `(pulse-highlight-start-face ((,class (:background "#AAAA33"))))
   `(pulse-highlight-face ((,class (:extend nil :background "#AAAA33"))))))

(provide-theme 'tok)

;; Local Variables:
;; no-byte-compile: t
;; End:

;;; tok-theme.el ends here
