(dockerfile-mode .
		 [(20210326 1812)
		  ((emacs
		    (24)))
		  "Major mode for editing Docker's Dockerfiles" single
		  ((:commit . "3b1374563f62d71aec11ebd33d37109459e54571")
		   (:url . "https://github.com/spotify/dockerfile-mode"))])
