(dockerfile-mode .
		 [(20220220 1439)
		  ((emacs
		    (24)))
		  "Major mode for editing Docker's Dockerfiles" single
		  ((:commit . "b63a3d12b7dea0cb9efc7f78d7ad5672ceab2a3f")
		   (:keywords "docker")
		   (:url . "https://github.com/spotify/dockerfile-mode"))])
