(dockerfile-mode .
		 [(20210301 52)
		  ((emacs
		    (24)))
		  "Major mode for editing Docker's Dockerfiles" single
		  ((:commit . "07dde72b0e356d772fb65b969bd6decfa166e4d7")
		   (:url . "https://github.com/spotify/dockerfile-mode"))])
