(dockerfile-mode .
		 [(20220220 1439)
		  ((emacs
		    (24)))
		  "Major mode for editing Docker's Dockerfiles" single
		  ((:commit . "11c43de04b128b7638cd98a1e80be2b661c18fbb")
		   (:keywords "docker")
		   (:url . "https://github.com/spotify/dockerfile-mode"))])
