(dockerfile-mode .
		 [(20210404 2224)
		  ((emacs
		    (24)))
		  "Major mode for editing Docker's Dockerfiles" single
		  ((:commit . "ad06a41259ff2961d603bf23a3a8fbd22dde2161")
		   (:url . "https://github.com/spotify/dockerfile-mode"))])
