(dockerfile-mode .
		 [(20220820 1433)
		  ((emacs
		    (24)))
		  "Major mode for editing Docker's Dockerfiles" single
		  ((:commit . "5e7096d451380d4b9a53dff2894adbe3590aae9f")
		   (:keywords "docker")
		   (:url . "https://github.com/spotify/dockerfile-mode"))])
