(dockerfile-mode .
		 [(20210215 1633)
		  ((emacs
		    (24)))
		  "Major mode for editing Docker's Dockerfiles" single
		  ((:commit . "b01f2ecdb6ce981e07e5caa4ec712904071ea26a")
		   (:url . "https://github.com/spotify/dockerfile-mode"))])
