(dockerfile-mode .
		 [(20210218 1746)
		  ((emacs
		    (24)))
		  "Major mode for editing Docker's Dockerfiles" single
		  ((:commit . "ed1d04c89cd8b53963f2dcae7cb3a46967e0abbf")
		   (:url . "https://github.com/spotify/dockerfile-mode"))])
