;;; soothe-theme.el --- A dark colorful theme. -*- lexical-binding: t; -*-
;;
;; Copyright (C) 2022 Jason Milkins
;;
;; Author: Jason Milkins <jasonm23@gmail.com>
;; Maintainer: Jason Milkins <jasonm23@gmail.com>
;; URL: https://github.com/jason/soothe-theme
;; Package-Version: 20220819.1453
;; Package-Commit: 66399ec22040b7a310a24707867ee6df625fd311
;; Version: 1.0.0
;; Package-Requires: ((emacs "24.3") (autothemer "0.2"))
;;
;; This file is not part of GNU Emacs.
;;
;;; License
;;
;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 3, or (at your option)
;; any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program; see the file COPYING.  If not, write to
;; the Free Software Foundation, Inc., 51 Franklin Street, Fifth
;; Floor, Boston, MA 02110-1301, USA.

;;; Commentary:
;;
;;  A dark colorful theme.
;;
;;; Code:

;; Local Variables:
;; eval: (when (fboundp 'rainbow-mode) (rainbow-mode +1))
;; End:
(require 'autothemer)

(unless (>= emacs-major-version 24)
  (error "Requires Emacs 24 or later"))


(autothemer-deftheme  soothe
                      "A dark colorful theme"
 ((((class color) (min-colors #xFFFFFF))) ;; GUI/24bit only
  (foreground       "#F4F1ED")
  (crem             "#F4F1ED")
  (snow-code        "#ECEAE5")
  (foam             "#E3E4E2")
  (dirty-crem       "#DBD9D4")
  (darker-crem      "#CECCC7")
  (gray-1           "#AAAAAA")
  (gray-2           "#828282")
  (background-dark-0 "#000000")
  (background-dark  "#0F0E11")
  (background       "#111013")
  (alt-background   "#121113")
  (dirty-crem-bg    "#2B2A2A")
  (darker-crem-bg   "#333030")
  (gray-3           "#333333")
  (gray-4           "#2A2A2A")
  (gray-5           "#252525")
  (gray-6           "#202020")
  (gray-1bg         "#0A0A0A")
  (gray-2bg         "#111111")
  (gray-3bg         "#141414")
  (gray-4bg         "#171717")
  (gray-5bg         "#1A1A1A")
  (gray-6bg         "#1E1E1E")

  (red-1            "#B14031")
  (orange-1         "#D9581A")
  (brown-1          "#8F672B")
  (yellow-1         "#CEB252")
  (green-1          "#779F43")
  (turquoise-1      "#0A545F")
  (blue-1           "#90A9C9")
  (purple-1         "#867AB5")

  (red-2            "#A24B2E")
  (orange-2         "#FF642A")
  (green-2          "#4C8F79")
  (turquoise-2      "#0E3E46")
  (blue-2           "#407A98")
  (purple-2         "#9891B5")

  (red-3            "#AA2010")
  (green-3          "#899F6D")
  (blue-3           "#0E9090")
  (purple-3         "#50486C")

  (red-4            "#660A0A")
  (blue-4           "#42557A")
  (purple-4         "#3B3358")

  (red-1bg          "#1D1717")
  (brown-1bg        "#2A2323")
  (orange-1bg       "#1F1813")
  (yellow-1bg       "#18140E")
  (green-1bg        "#1D2321")
  (turquoise-1bg    "#06181C")
  (blue-1bg         "#22272F")
  (purple-1bg       "#1F1E25")

  (red-2bg          "#251F20")
  (green-2bg        "#1D2321")
  (turquoise-2bg    "#051316")
  (blue-2bg         "#21343E")

  (blue-3bg         "#162328")
  (purple-2bg       "#353048")

  (blue-4bg         "#1B2128")
  (purple-3bg       "#282436")

  (hl-line          "#15252A")
  (selection        "#16273A")

  (soothe-rainbow-delimiters-0 "#894B30")
  (soothe-rainbow-delimiters-1 "#284E5B")
  (soothe-rainbow-delimiters-2 "#B2887A")
  (soothe-rainbow-delimiters-3 "#37833B")
  (soothe-rainbow-delimiters-4 "#3F5355")
  (soothe-rainbow-delimiters-5 "#5B6192")
  (soothe-rainbow-delimiters-6 "#8A6558")
  (soothe-rainbow-delimiters-7 "#B2A276")
  (soothe-rainbow-delimiters-8 "#52B275")
  (soothe-rainbow-delimiters-9 "#AC3B63"))


 ((default                                   (:foreground foreground  :background background))
  (cursor                                    (:background orange-1))
  (region                                    (:foreground nil          :background selection))
  (highlight                                 (:foreground blue-3      :background blue-3bg))
  (hl-line                                   (:background hl-line))
  (minibuffer-prompt                         (:foreground orange-1    :background orange-1bg))
  (escape-glyph                              (:foreground red-1       :background purple-1bg))
  (error                                     (:foreground red-1       :background red-1bg))
  (font-lock-builtin-face                    (:foreground red-2       :background red-1bg))
  (font-lock-constant-face                   (:foreground purple-1    :background purple-1bg))
  (font-lock-comment-face                    (:foreground purple-1    :background alt-background :italic t))
  (font-lock-comment-delimiter-face          (:foreground turquoise-1 :background alt-background :italic t))
  (font-lock-doc-face                        (:foreground blue-3      :background gray-1bg))
  (font-lock-doc-string-face                 (:foreground blue-3      :background gray-1bg))
  (font-lock-function-name-face              (:foreground red-1       :background red-1bg))
  (font-lock-keyword-face                    (:foreground orange-1    :background orange-1bg))
  (font-lock-negation-char-face              (:foreground yellow-1    :background yellow-1bg))
  (font-lock-preprocessor-face               (:foreground orange-1    :background orange-1bg))
  (font-lock-string-face                     (:foreground blue-3      :background turquoise-2bg))
  (font-lock-type-face                       (:foreground red-2       :background red-1bg        :bold nil))
  (font-lock-variable-name-face              (:foreground blue-1      :background blue-1bg))
  (font-lock-warning-face                    (:foreground red-2       :background red-2bg))
  (link                                      (:foreground blue-1      :background blue-1bg))
  (link-visited                              (:foreground blue-3      :background blue-4bg))
  (fringe                                    (:background gray-3bg))
  (vertical-border                           (:foreground gray-4      :background background))
  (mode-line                                 (:foreground gray-2      :background gray-3bg  :box nil))
  (mode-line-inactive                        (:foreground gray-5      :background gray-2bg  :inherit 'mode-line))
  (mode-line-highlight                       (:foreground red-1))
  (mode-line-buffer-id                       (:foreground orange-1))
  (mode-line-emphasis                        (:bold))
  (which-func                                (:foreground blue-1))
  (isearch                                   (:foreground foam        :background purple-3))
  (isearch-fail                              (:foreground foam        :background red-4))
  (lazy-highlight                            (:foreground purple-1    :background green-2bg))
  (ac-selection-face                         (:foreground dirty-crem  :background dirty-crem-bg))
  (ac-candidate-face                         (:foreground background  :background dirty-crem))
  (ac-yasnippet-candidate-face               (:foreground background  :background green-2))
  (ac-yasnippet-selection-face               (:foreground foam        :background dirty-crem-bg))
  (ac-gtags-candidate-face                   (:foreground background  :background purple-3))
  (ac-gtags-selection-face                   (:foreground dirty-crem  :background dirty-crem-bg))
  (ac-candidate-mouse-face                   (:foreground foam        :background turquoise-1))
  (ac-completion-face                        (:foreground snow-code   :background purple-3bg :underline t))
  (popup-tip-face                            (:foreground dirty-crem     :background dirty-crem-bg))
  (tooltip                                   (:foreground dirty-crem-bg  :background dirty-crem))
  (dired-filename                            (:foreground purple-1    :background purple-1bg))
  (dired-directory                           (:foreground purple-1    :background purple-1bg))
  (dired-flagged                             (:foreground red-1       :background orange-1bg))
  (dired-header                              (:foreground orange-1    :background background))
  (dired-ignored                             (:foreground turquoise-1 :background background))
  (dired-mark                                (:foreground orange-2    :background background))
  (dired-marked                              (:foreground green-3     :background orange-1bg))
  (dired-perm-write                          (:foreground foam        :background background))
  (dired-symlink                             (:foreground blue-1      :background blue-4bg))
  (dired-warning                             (:foreground red-1       :background red-2bg))

  (diredfl-filename                          (:inherit 'dired-filename))
  (diredfl-directory                         (:inherit 'dired-directory))
  (diredfl-flagged                           (:inherit 'dired-flagged))
  (diredfl-header                            (:inherit 'dired-header))
  (diredfl-ignored                           (:inherit 'dired-ignored))
  (diredfl-mark                              (:inherit 'dired-mark))
  (diredfl-marked                            (:inherit 'dired-marked))
  (diredfl-perm-write                        (:inherit 'dired-perm-write))
  (diredfl-symlink                           (:inherit 'dired-symlink))
  (diredfl-warning                           (:inherit 'dired-warning))

  (js3-error-face                            (:underline red-1        :background red-1bg))
  (js3-warning-face                          (:underline yellow-1     :background yellow-1bg))
  (js3-external-variable-face                (:foreground purple-1    :background purple-1bg))
  (js3-function-param-face                   (:foreground blue-3      :background blue-3bg))
  (js3-instance-member-face                  (:foreground dirty-crem  :background purple-1bg))
  (js3-magic-paren-face                      (:foreground snow-code   :background purple-1bg))
  (js3-private-function-call-face            (:foreground orange-1    :background orange-1bg))
  (js3-private-member-face                   (:foreground orange-2    :background orange-1bg))
  (js3-jsdoc-html-tag-delimiter-face         (:foreground blue-4      :background blue-2bg))
  (js3-jsdoc-html-tag-name-face              (:foreground foam        :background blue-3bg))
  (js3-jsdoc-tag-face                        (:foreground green-3     :background green-2bg))
  (js3-jsdoc-type-face                       (:foreground green-2     :background green-2bg))
  (js3-jsdoc-value-face                      (:foreground green-1     :background green-1bg))
  (diff-added                                (:foreground green-3     :background green-2bg))
  (diff-removed                              (:foreground red-1       :background red-1bg))
  (diff-file-header                          (:foreground orange-1    :background orange-1bg))
  (diff-context                              (:foreground foam))
  (diff-hunk-header                          (:foreground purple-1    :background purple-1bg))
  (linum                                     (:foreground gray-6 :background alt-background))
  (show-paren-match                          (:foreground foam        :background orange-1))
  (show-paren-mismatch                       (:foreground orange-1    :background red-2bg))
  (ido-only-match                            (:foreground green-1     :background green-1bg))
  (ido-subdir                                (:foreground purple-1    :background purple-1bg))
  (ido-first-match                           (:foreground orange-1    :background orange-1bg))
  (ido-incomplete-regexp                     (:foreground red-1       :background orange-1bg))
  (ido-indicator                             (:foreground turquoise-1 :background turquoise-1bg))
  (ido-virtual                               (:foreground green-3     :background turquoise-1bg))
  (whitespace-empty                          (:foreground yellow-1    :background turquoise-2bg))
  (whitespace-hspace                         (:foreground turquoise-2 :background turquoise-2bg))
  (whitespace-indentation                    (:foreground turquoise-2 :background turquoise-2bg))
  (whitespace-line                           (:foreground orange-1    :background turquoise-2bg))
  (whitespace-newline                        (:foreground turquoise-2 :background turquoise-2bg))
  (whitespace-space                          (:foreground turquoise-2 :background turquoise-2bg))
  (whitespace-space-after-tab                (:foreground turquoise-2 :background turquoise-2bg))
  (whitespace-tab                            (:foreground turquoise-2 :background turquoise-2bg))
  (whitespace-trailing                       (:foreground red-1       :background turquoise-2bg))
  (flyspell-incorrect                        (:underline red-2))
  (flyspell-duplicate                        (:underline green-2))
  (flymake-errline                           (:underline red-2        :background nil :inherit nil))
  (flymake-warnline                          (:underline green-2      :background nil :inherit nil))
  (dropdown-list-selection-face              (:foreground foam        :background purple-1bg))
  (dropdown-list-face                        (:foreground background  :background foam))

  (git-gutter:added                          (:foreground green-1     :background green-2bg))
  (git-gutter:deleted                        (:foreground red-1       :background red-1bg))
  (git-gutter:modified                       (:foreground purple-1    :background purple-1bg))
  (git-gutter:unchanged                      (:background yellow-1bg))

  (magit-item-highlight                      (:background purple-3bg))
  (magit-branch                              (:foreground green-2     :background green-2bg))
  (magit-branch-remote                       (:foreground green-2     :background green-2bg))
  (magit-whitespace-warning-face             (:foreground red-3       :background red-1bg))
  (magit-section-heading                     (:foreground orange-1    :background purple-1bg))
  (magit-section-title                       (:foreground purple-1    :background purple-1bg))
  (magit-section-highlight                   (:foreground purple-1    :background purple-1bg))
  (magit-section-highlight-selection         (:foreground purple-1    :background purple-1bg))
  (magit-header                              (:foreground orange-1    :background orange-1bg))
  (magit-item-mark                           (:foreground green-1))
  (magit-diff-merge-proposed                 (:foreground foam))
  (magit-diff-merge-current                  (:foreground blue-1))
  (magit-diff-merge-separator                (:foreground blue-2))
  (magit-log-author                          (:foreground purple-1    :background purple-1bg))
  (magit-log-graph                           (:foreground blue-2      :background blue-2bg))
  (magit-log-head-label-bisect-good          (:foreground turquoise-1 :background turquoise-1bg))
  (magit-log-head-label-local                (:foreground foam        :background turquoise-1bg))
  (magit-log-head-label-remote               (:foreground foam        :background purple-2bg))
  (magit-log-message                         (:foreground dirty-crem  :background background))
  (magit-log-date                            (:foreground blue-4      :background background))
  (magit-log-head-label-bisect-bad           (:foreground red-1       :background red-1bg))
  (magit-log-head-label-default              (:foreground foam        :background turquoise-1bg))
  (magit-log-head-label-patches              (:foreground blue-2      :background blue-1bg))
  (magit-log-head-label-tags                 (:foreground orange-1    :background orange-1bg))
  (magit-log-sha1                            (:foreground turquoise-1 :background turquoise-1bg))

  (diff-hl-insert                            (:foreground green-1     :background green-2bg))
  (diff-hl-delete                            (:foreground red-1       :background red-1bg))
  (diff-hl-change                            (:foreground purple-1    :background purple-1bg))

  (iedit-occurrence                          (:foreground green-3   :background orange-1bg))
  (iedit-read-only-occurrence                (:foreground red-1     :background orange-1bg))
  (highlight-indentation-face                (:background background-dark))
  (highlight-indentation-current-column-face (:background gray-5))
  (ecb-default-general-face                  (:foreground gray-1      :background gray-1bg))
  (ecb-default-highlight-face                (:foreground red-1       :background red-1bg))
  (ecb-method-face                           (:foreground red-1       :background red-1bg))
  (ecb-tag-header-face                       (:background blue-2bg))
  (org-date                                  (:foreground purple-1    :background purple-1bg))
  (org-done                                  (:foreground green-1     :background green-1bg))
  (org-hide                                  (:foreground gray-3      :background gray-1bg))
  (org-link                                  (:foreground blue-1      :background blue-1bg))
  (org-todo                                  (:foreground red-1       :background red-1bg))
  (cua-global-mark                           (:foreground foam :background turquoise-1))
  (cua-rectangle                             (:foreground foam :background purple-4))
  (cua-rectangle-noselect                    (:foreground foam :background orange-1))
  (hl-sexp-face                              (:background turquoise-2bg))

  (orderless-match-face-0                    (:foreground crem))
  (orderless-match-face-1                    (:foreground foam))
  (orderless-match-face-2                    (:foreground dirty-crem))
  (orderless-match-face-3                    (:foreground darker-crem))

  (vertico-posframe                          (:background background-dark))
  (vertico-posframe-border                   (:background background-dark-0))
  (vertico-posframe-border-2                 (:background alt-background))
  (vertico-posframe-border-3                 (:background dirty-crem-bg))
  (vertico-posframe-border-4                 (:background darker-crem-bg))

  (which-key-command-description-face        (:inherit 'font-lock-function-name-face))
  (which-key-group-description-face          (:inherit 'font-lock-keyword-face))
  (which-key-highlighted-command-face        (:underline t :inherit 'which-key-command-description-face))
  (which-key-key-face                        (:inherit 'font-lock-constant-face))
  (which-key-local-map-description-face      (:inherit 'which-key-command-description-face))
  (which-key-note-face                       (:inherit 'which-key-separator-face))
  (which-key-separator-face                  (:inherit 'font-lock-comment-face))
  (which-key-special-key-face                (:weight 'bold :inverse-video t :inherit 'which-key-key-face))

  (rainbow-delimiters-depth-1-face           (:foreground soothe-rainbow-delimiters-0))
  (rainbow-delimiters-depth-2-face           (:foreground soothe-rainbow-delimiters-1))
  (rainbow-delimiters-depth-3-face           (:foreground soothe-rainbow-delimiters-2))
  (rainbow-delimiters-depth-4-face           (:foreground soothe-rainbow-delimiters-3))
  (rainbow-delimiters-depth-5-face           (:foreground soothe-rainbow-delimiters-4))
  (rainbow-delimiters-depth-6-face           (:foreground soothe-rainbow-delimiters-5))
  (rainbow-delimiters-depth-7-face           (:foreground soothe-rainbow-delimiters-6))
  (rainbow-delimiters-depth-8-face           (:foreground soothe-rainbow-delimiters-7))
  (rainbow-delimiters-depth-9-face           (:foreground soothe-rainbow-delimiters-8))
  (rainbow-delimiters-unmatched-face         (:foreground soothe-rainbow-delimiters-9)))

 (custom-theme-set-variables 'soothe
                            `(pos-tip-foreground-color ,foreground)
                            `(pos-tip-background-color ,background)
                            `(ansi-color-names-vector [,background
                                                       ,red-1
                                                       ,green-1
                                                       ,yellow-1
                                                       ,blue-1
                                                       ,purple-1
                                                       ,blue-3
                                                       ,foreground])))


;;; -- TODO...
;;;
;;; List of face to theme... perhaps....

;; (diff-changed                              (:foreground nil :background nil )
;; (diff-function                             (:foreground nil :background nil )
;; (diff-header                               (:foreground nil :background nil )
;; (diff-index                                (:foreground nil :background nil )
;; (diff-indicator-added                      (:foreground nil :background nil )
;; (diff-indicator-changed                    (:foreground nil :background nil )
;; (diff-indicator-removed                    (:foreground nil :background nil )
;; (diff-nonexistent                          (:foreground nil :background nil )
;; (diff-refine-added                         (:foreground nil :background nil )
;; (diff-refine-change                        (:foreground nil :background nil )
;; (diff-refine-removed                       (:foreground nil :background nil )
;; (Man-overstrike                            (:foreground nil :background nil )
;; (Man-reverse                               (:foreground nil :background nil )
;; (Man-underline                             (:foreground nil :background nil )
;; (bold                                      (:foreground nil :background nil )
;; (bold-italic                               (:foreground nil :background nil )
;; (border                                    (:foreground nil :background nil )
;; (buffer-menu-buffer                        (:foreground nil :background nil )
;; (button                                    (:foreground nil :background nil )
;; (c-annotation-face                         (:foreground nil :background nil )
;; (change-log-acknowledgment                 (:foreground nil :background nil )
;; (change-log-conditionals                   (:foreground nil :background nil )
;; (change-log-date                           (:foreground nil :background nil )
;; (change-log-email                          (:foreground nil :background nil )
;; (change-log-file                           (:foreground nil :background nil )
;; (change-log-function                       (:foreground nil :background nil )
;; (change-log-list                           (:foreground nil :background nil )
;; (change-log-name                           (:foreground nil :background nil )
;; (comint-highlight-input                    (:foreground nil :background nil )
;; (comint-highlight-prompt                   (:foreground nil :background nil )
;; (completions-annotations                   (:foreground nil :background nil )
;; (completions-common-part                   (:foreground nil :background nil )
;; (completions-first-difference              (:foreground nil :background nil )
;; (custom-button                             (:foreground nil :background nil )
;; (custom-button-mouse                       (:foreground nil :background nil )
;; (custom-button-pressed                     (:foreground nil :background nil )
;; (custom-button-pressed-unraised            (:foreground nil :background nil )
;; (custom-button-unraised                    (:foreground nil :background nil )
;; (custom-changed                            (:foreground nil :background nil )
;; (custom-comment                            (:foreground nil :background nil )
;; (custom-comment-tag                        (:foreground nil :background nil )
;; (custom-documentation                      (:foreground nil :background nil )
;; (custom-face-tag                           (:foreground nil :background nil )
;; (custom-group-subtitle                     (:foreground nil :background nil )
;; (custom-group-tag                          (:foreground nil :background nil )
;; (custom-group-tag-1                        (:foreground nil :background nil )
;; (custom-invalid                            (:foreground nil :background nil )
;; (custom-link                               (:foreground nil :background nil )
;; (custom-modified                           (:foreground nil :background nil )
;; (custom-rogue                              (:foreground nil :background nil )
;; (custom-saved                              (:foreground nil :background nil )
;; (custom-set                                (:foreground nil :background nil )
;; (custom-state                              (:foreground nil :background nil )
;; (custom-themed                             (:foreground nil :background nil )
;; (custom-variable-button                    (:foreground nil :background nil )
;; (custom-variable-tag                       (:foreground nil :background nil )
;; (custom-visibility                         (:foreground nil :background nil )
;; (ecb-default-general-face                  (:foreground nil :background nil )
;; (ecb-default-highlight-face                (:foreground nil :background nil )
;; (ecb-method-face                           (:foreground nil :background nil )
;; (ecb-tag-header-face                       (:foreground nil :background nil )
;; (error                                     (:foreground nil :background nil )
;; (escape-glyph                              (:foreground nil :background nil )
;; (file-name-shadow                          (:foreground nil :background nil )
;; (fixed-pitch                               (:foreground nil :background nil )
;; (glyphless-char                            (:foreground nil :background nil )
;; (header-line                               (:foreground nil :background nil )
;; (help-argument-name                        (:foreground nil :background nil )
;; (hi-black-b                                (:foreground nil :background nil )
;; (hi-black-hb                               (:foreground nil :background nil )
;; (hi-blue                                   (:foreground nil :background nil )
;; (hi-blue-b                                 (:foreground nil :background nil )
;; (hi-green                                  (:foreground nil :background nil )
;; (hi-green-b                                (:foreground nil :background nil )
;; (hi-pink                                   (:foreground nil :background nil )
;; (hi-red-b                                  (:foreground nil :background nil )
;; (hi-yellow                                 (:foreground nil :background nil )
;; (hideshowvis-hidable-face                  (:foreground nil :background nil )
;; (highlight                                 (:foreground nil :background nil )
;; (highlight-changes                         (:foreground nil :background nil )
;; (highlight-changes-delete                  (:foreground nil :background nil )
;; (highlight-indentation-current-column-face (:foreground nil :background nil )
;; (highlight-indentation-face                (:foreground nil :background nil )
;; (hl-line                                   (:foreground nil :background nil )
;; (hs-face                                   (:foreground nil :background nil )
;; (hs-fringe-face                            (:foreground nil :background nil )
;; (info-header-node                          (:foreground nil :background nil )
;; (info-header-xref                          (:foreground nil :background nil )
;; (info-menu-header                          (:foreground nil :background nil )
;; (info-menu-star                            (:foreground nil :background nil )
;; (info-node                                 (:foreground nil :background nil )
;; (info-title-1                              (:foreground nil :background nil )
;; (info-title-2                              (:foreground nil :background nil )
;; (info-title-3                              (:foreground nil :background nil )
;; (info-title-4                              (:foreground nil :background nil )
;; (info-xref                                 (:foreground nil :background nil )
;; (info-xref-visited                         (:foreground nil :background nil )
;; (italic                                    (:foreground nil :background nil )
;; (lazy-highlight                            (:foreground nil :background nil )
;; (link                                      (:foreground nil :background nil )
;; (link-visited                              (:foreground nil :background nil )
;; (log-edit-header                           (:foreground nil :background nil )
;; (log-edit-summary                          (:foreground nil :background nil )
;; (log-edit-unknown-header                   (:foreground nil :background nil )
;; (mac-ts-caret-position                     (:foreground nil :background nil )
;; (mac-ts-converted-text                     (:foreground nil :background nil )
;; (mac-ts-raw-text                           (:foreground nil :background nil )
;; (mac-ts-selected-converted-text            (:foreground nil :background nil )
;; (match                                     (:foreground nil :background nil )
;; (menu                                      (:foreground nil :background nil )
;; (message-cited-text                        (:foreground nil :background nil )
;; (message-header-cc                         (:foreground nil :background nil )
;; (message-header-name                       (:foreground nil :background nil )
;; (message-header-newsgroups                 (:foreground nil :background nil )
;; (message-header-other                      (:foreground nil :background nil )
;; (message-header-subject                    (:foreground nil :background nil )
;; (message-header-to                         (:foreground nil :background nil )
;; (message-header-xheader                    (:foreground nil :background nil )
;; (message-mml                               (:foreground nil :background nil )
;; (message-separator                         (:foreground nil :background nil )
;; (minibuffer-prompt                         (:foreground nil :background nil )
;; (mouse                                     (:foreground nil :background nil )
;; (next-error                                (:foreground nil :background nil )
;; (nobreak-space                             (:foreground nil :background nil )
;; (org-date                                  (:foreground nil :background nil )
;; (org-done                                  (:foreground nil :background nil )
;; (org-hide                                  (:foreground nil :background nil )
;; (org-link                                  (:foreground nil :background nil )
;; (org-todo                                  (:foreground nil :background nil )
;; (powerline-active1                         (:foreground nil :background nil )
;; (powerline-active2                         (:foreground nil :background nil )
;; (powerline-inactive1                       (:foreground nil :background nil )
;; (powerline-inactive2                       (:foreground nil :background nil )
;; (proced-mark                               (:foreground nil :background nil )
;; (proced-marked                             (:foreground nil :background nil )
;; (proced-sort-header                        (:foreground nil :background nil )
;; (query-replace                             (:foreground nil :background nil )
;; (rcirc-bright-nick                         (:foreground nil :background nil )
;; (rcirc-dim-nick                            (:foreground nil :background nil )
;; (rcirc-keyword                             (:foreground nil :background nil )
;; (rcirc-my-nick                             (:foreground nil :background nil )
;; (rcirc-nick-in-message                     (:foreground nil :background nil )
;; (rcirc-nick-in-message-full-line           (:foreground nil :background nil )
;; (rcirc-other-nick                          (:foreground nil :background nil )
;; (rcirc-prompt                              (:foreground nil :background nil )
;; (rcirc-server                              (:foreground nil :background nil )
;; (rcirc-server-prefix                       (:foreground nil :background nil )
;; (rcirc-timestamp                           (:foreground nil :background nil )
;; (rcirc-track-keyword                       (:foreground nil :background nil )
;; (rcirc-track-nick                          (:foreground nil :background nil )
;; (rcirc-url                                 (:foreground nil :background nil )
;; (rst-adornment                             (:foreground nil :background nil )
;; (rst-block                                 (:foreground nil :background nil )
;; (rst-comment                               (:foreground nil :background nil )
;; (rst-definition                            (:foreground nil :background nil )
;; (rst-directive                             (:foreground nil :background nil )
;; (rst-emphasis1                             (:foreground nil :background nil )
;; (rst-emphasis2                             (:foreground nil :background nil )
;; (rst-external                              (:foreground nil :background nil )
;; (rst-level-1                               (:foreground nil :background nil )
;; (rst-level-2                               (:foreground nil :background nil )
;; (rst-level-3                               (:foreground nil :background nil )
;; (rst-level-4                               (:foreground nil :background nil )
;; (rst-level-5                               (:foreground nil :background nil )
;; (rst-level-6                               (:foreground nil :background nil )
;; (rst-literal                               (:foreground nil :background nil )
;; (rst-reference                             (:foreground nil :background nil )
;; (rst-transition                            (:foreground nil :background nil )
;; (scroll-bar                                (:foreground nil :background nil )
;; (secondary-selection                       (:foreground nil :background nil )
;; (shadow                                    (:foreground nil :background nil )
;; (show-paren-match                          (:foreground nil :background nil )
;; (show-paren-mismatch                       (:foreground nil :background nil )
;; (speedbar-button-face                      (:foreground nil :background nil )
;; (speedbar-directory-face                   (:foreground nil :background nil )
;; (speedbar-file-face                        (:foreground nil :background nil )
;; (speedbar-highlight-face                   (:foreground nil :background nil )
;; (speedbar-selected-face                    (:foreground nil :background nil )
;; (speedbar-separator-face                   (:foreground nil :background nil )
;; (speedbar-tag-face                         (:foreground nil :background nil )
;; (success                                   (:foreground nil :background nil )
;; (tool-bar                                  (:foreground nil :background nil )
;; (trailing-whitespace                       (:foreground nil :background nil )
;; (underline                                 (:foreground nil :background nil )
;; (variable-pitch                            (:foreground nil :background nil )
;; (vertical-border                           (:foreground nil :background nil )
;; (w3m-anchor                                (:foreground nil :background nil )
;; (w3m-arrived-anchor                        (:foreground nil :background nil )
;; (w3m-bold                                  (:foreground nil :background nil )
;; (w3m-current-anchor                        (:foreground nil :background nil )
;; (w3m-form-button                           (:foreground nil :background nil )
;; (w3m-form-button-mouse                     (:foreground nil :background nil )
;; (w3m-form-button-pressed                   (:foreground nil :background nil )
;; (w3m-header-line-location-content          (:foreground nil :background nil )
;; (w3m-header-line-location-title            (:foreground nil :background nil )
;; (w3m-history-current-url                   (:foreground nil :background nil )
;; (w3m-image                                 (:foreground nil :background nil )
;; (w3m-image-anchor                          (:foreground nil :background nil )
;; (w3m-insert                                (:foreground nil :background nil )
;; (w3m-italic                                (:foreground nil :background nil )
;; (w3m-strike-through                        (:foreground nil :background nil )
;; (w3m-tab-background                        (:foreground nil :background nil )
;; (w3m-tab-mouse                             (:foreground nil :background nil )
;; (w3m-tab-selected                          (:foreground nil :background nil )
;; (w3m-tab-selected-background               (:foreground nil :background nil )
;; (w3m-tab-selected-retrieving               (:foreground nil :background nil )
;; (w3m-tab-unselected                        (:foreground nil :background nil )
;; (w3m-tab-unselected-retrieving             (:foreground nil :background nil )
;; (w3m-tab-unselected-unseen                 (:foreground nil :background nil )
;; (w3m-underline                             (:foreground nil :background nil )
;; (warning                                   (:foreground nil :background nil )
;; (whitespace-empty                          (:foreground nil :background nil )
;; (whitespace-hspace                         (:foreground nil :background nil )
;; (whitespace-indentation                    (:foreground nil :background nil )
;; (whitespace-line                           (:foreground nil :background nil )
;; (whitespace-newline                        (:foreground nil :background nil )
;; (whitespace-space                          (:foreground nil :background nil )
;; (whitespace-space-after-tab                (:foreground nil :background nil )
;; (whitespace-tab                            (:foreground nil :background nil )
;; (whitespace-trailing                       (:foreground nil :background nil )
;; (widget-button                             (:foreground nil :background nil )
;; (widget-button-pressed                     (:foreground nil :background nil )
;; (widget-documentation                      (:foreground nil :background nil )
;; (widget-field                              (:foreground nil :background nil )
;; (widget-inactive                           (:foreground nil :background nil )
;; (widget-single-line-field                  (:foreground nil :background nil )
;; (woman-addition                            (:foreground nil :background nil )
;; (woman-bold                                (:foreground nil :background nil )
;; (woman-italic                              (:foreground nil :background nil )
;; (woman-unknown                             (:foreground nil :background nil )
;; (yas--field-debug-face                     (:foreground nil :background nil )
;; (yas-field-highlight-face                  (:foreground nil :background nil )
;; (gnus-group-mail-1                         (:foreground nil :background nil )
;; (gnus-group-mail-1-empty                   (:foreground nil :background nil )
;; (gnus-group-mail-2                         (:foreground nil :background nil )
;; (gnus-group-mail-2-empty                   (:foreground nil :background nil )
;; (gnus-group-mail-3                         (:foreground nil :background nil )
;; (gnus-group-mail-3-empty                   (:foreground nil :background nil )
;; (gnus-group-mail-low                       (:foreground nil :background nil )
;; (gnus-group-mail-low-empty                 (:foreground nil :background nil )
;; (gnus-group-news-1                         (:foreground nil :background nil )
;; (gnus-group-news-1-empty                   (:foreground nil :background nil )
;; (gnus-group-news-2                         (:foreground nil :background nil )
;; (gnus-group-news-2-empty                   (:foreground nil :background nil )
;; (gnus-group-news-3                         (:foreground nil :background nil )
;; (gnus-group-news-3-empty                   (:foreground nil :background nil )
;; (gnus-group-news-4                         (:foreground nil :background nil )
;; (gnus-group-news-4-empty                   (:foreground nil :background nil )
;; (gnus-group-news-5                         (:foreground nil :background nil )
;; (gnus-group-news-5-empty                   (:foreground nil :background nil )
;; (gnus-group-news-6                         (:foreground nil :background nil )
;; (gnus-group-news-6-empty                   (:foreground nil :background nil )
;; (gnus-group-news-low                       (:foreground nil :background nil )
;; (gnus-group-news-low-empty                 (:foreground nil :background nil )
;; (gnus-splash                               (:foreground nil :background nil )
;; (gnus-summary-cancelled                    (:foreground nil :background nil )
;; (gnus-summary-high-ancient                 (:foreground nil :background nil )
;; (gnus-summary-high-read                    (:foreground nil :background nil )
;; (gnus-summary-high-ticked                  (:foreground nil :background nil )
;; (gnus-summary-high-undownloaded            (:foreground nil :background nil )
;; (gnus-summary-high-unread                  (:foreground nil :background nil )
;; (gnus-summary-low-ancient                  (:foreground nil :background nil )
;; (gnus-summary-low-read                     (:foreground nil :background nil )
;; (gnus-summary-low-ticked                   (:foreground nil :background nil )
;; (gnus-summary-low-undownloaded             (:foreground nil :background nil )
;; (gnus-summary-low-unread                   (:foreground nil :background nil )
;; (gnus-summary-normal-ancient               (:foreground nil :background nil )
;; (gnus-summary-normal-read                  (:foreground nil :background nil )
;; (gnus-summary-normal-ticked                (:foreground nil :background nil )
;; (gnus-summary-normal-undownloaded          (:foreground nil :background nil )
;; (gnus-summary-normal-unread                (:foreground nil :background nil )
;; (gnus-summary-selected                     (:foreground nil :background nil )
;; (helm-M-x-key                              (:foreground nil :background nil )
;; (helm-action                               (:foreground nil :background nil )
;; (helm-bookmark-addressbook                 (:foreground nil :background nil )
;; (helm-bookmark-directory                   (:foreground nil :background nil )
;; (helm-bookmark-file                        (:foreground nil :background nil )
;; (helm-bookmark-gnus                        (:foreground nil :background nil )
;; (helm-bookmark-info                        (:foreground nil :background nil )
;; (helm-bookmark-man                         (:foreground nil :background nil )
;; (helm-bookmark-w3m                         (:foreground nil :background nil )
;; (helm-buffer-not-saved                     (:foreground nil :background nil )
;; (helm-buffer-process                       (:foreground nil :background nil )
;; (helm-buffer-saved-out                     (:foreground nil :background nil )
;; (helm-buffer-size                          (:foreground nil :background nil )
;; (helm-candidate-number                     (:foreground nil :background nil )
;; (helm-ff-directory                         (:foreground nil :background nil )
;; (helm-ff-executable                        (:foreground nil :background nil )
;; (helm-ff-file                              (:foreground nil :background nil )
;; (helm-ff-invalid-symlink                   (:foreground nil :background nil )
;; (helm-ff-prefix                            (:foreground nil :background nil )
;; (helm-ff-symlink                           (:foreground nil :background nil )
;; (helm-grep-cmd-line                        (:foreground nil :background nil )
;; (helm-grep-file                            (:foreground nil :background nil )
;; (helm-grep-finish                          (:foreground nil :background nil )
;; (helm-grep-lineno                          (:foreground nil :background nil )
;; (helm-grep-match                           (:foreground nil :background nil )
;; (helm-grep-running                         (:foreground nil :background nil )
;; (helm-header                               (:foreground nil :background nil )
;; (helm-helper                               (:foreground nil :background nil )
;; (helm-history-deleted                      (:foreground nil :background nil )
;; (helm-history-remote                       (:foreground nil :background nil )
;; (helm-match                                (:foreground nil :background nil )
;; (helm-moccur-buffer                        (:foreground nil :background nil )
;; (helm-selection                            (:foreground nil :background nil )
;; (helm-selection-line                       (:foreground nil :background nil )
;; (helm-separator                            (:foreground nil :background nil )
;; (helm-source-header                        (:foreground nil :background nil )
;; (helm-visible-mark                         (:foreground nil :background nil )
;; (popup-face                                (:foreground nil :background nil )
;; (popup-isearch-match                       (:foreground nil :background nil )
;; (popup-menu-face                           (:foreground nil :background nil )
;; (popup-menu-mouse-face                     (:foreground nil :background nil )
;; (popup-menu-selection-face                 (:foreground nil :background nil )
;; (popup-menu-summary-face                   (:foreground nil :background nil )
;; (popup-scroll-bar-background-face          (:foreground nil :background nil )
;; (popup-scroll-bar-foreground-face          (:foreground nil :background nil )
;; (popup-summary-face                        (:foreground nil :background nil )
;; (compilation-column-number                 (:foreground ,foam        :background ,background                    )
;; (compilation-error                         (:foreground ,foam        :background ,background                    )
;; (compilation-info                          (:foreground ,foam        :background ,background                    )
;; (compilation-line-number                   (:foreground ,foam        :background ,background                    )
;; (compilation-mode-line-exit                (:foreground ,foam        :background ,background                    )
;; (compilation-mode-line-fail                (:foreground ,foam        :background ,background                    )
;; (compilation-mode-line-run                 (:foreground ,foam        :background ,background                    )
;; (compilation-warning                       (:foreground ,foam        :background ,background                    )
;; (completions-annotations                   (:foreground ,foam        :background ,background                    )
;; (completions-common-part                   (:foreground ,foam        :background ,background                    )
;; (completions-first-difference              (:foreground ,foam        :background ,background                    )

;; Local Variables:
;; eval: (when (fboundp 'rainbow-mode) (rainbow-mode +1))
;;
;;


(provide-theme 'soothe)
;;; soothe-theme.el ends here
